### ISSUE TITLE
Analytics listenerconfigurations error after WUM update in APIM Analytics 2.6.0

### ISSUE THREAD

**Issue by niruhan** [wso2/analytics-apim#1001]
**Description:**
while trying to use store queries or to view the Analytics tab in the Store or the Publisher the below error is thrown.

Unable to find property 'keyStorePass' on class: org.wso2.transport.http.netty.config.ListenerConfiguration

netty-transports.yml file's configuration change that should be done in order to overcome this

**Affected Product Version:**
2.6.0

**OS, DB, other environment details and versions:**    
MacOS Mojave 10.14.3

**Steps to reproduce:**
Start the dashboard and try visiting the url

**Comment by fazlan-nazeem** [comment]
This issue was introduced via wum update and has been resolved with latest updates.
