### ISSUE TITLE
 DCR application creation error in analytics dashboard profile.

### ISSUE THREAD

**Issue by kasun-bandara** [wso2/analytics-apim#1039]
**Description:**
The following error occurs in the DCR application creation since the **201 response is not accepted** from the External IDP. We may need to accept the 201 response as well other than 200 since it may be the most valid response code as this operation led to a resource creation. 

ERROR {org.wso2.analytics.apim.idp.client.ApimIdPClient} - Error occurred while DCR application creation. Error: '{"grant_types":[],"client_secret_expires_at":"0","redirect_uris":[null],"client_secret":"xxxxxxx","client_name":"xxxx","client_id":"xxxx"}'. **Status Code: '201'.**

**Suggested Labels:**
APIM 3.1.0-beta

**Suggested Assignees:**

**Affected Product Version:**
APIM 3.1.0-beta
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by fazlan-nazeem** [comment]
We assume this was due to providing the external IDPs URLs in auth configs instead of publisher Url. Hence closing.
