### ISSUE TITLE
Labels overlap with content in developer dashboard when large number of APIs or applications are created

### ISSUE THREAD

**Issue by Ketharan** [wso2/analytics-apim#1078]
**Description:**
Registered application users and API usage of application widgets analytics developer dashboard show the behavior.
![more_apps](https://user-images.githubusercontent.com/25489203/76859473-6dc53f00-687f-11ea-8d8a-83ebbfe7e038.png)
![more_apis](https://user-images.githubusercontent.com/25489203/76859492-7158c600-687f-11ea-97db-aab6674d8b42.png)

**Affected Product Version:**
3.1.0-rc1

**OS, DB, other environment details and versions:**    
Firefox (74.0) in ubuntu

**Comment by fazlan-nazeem** [comment]
@pahans  ideally we should have a limit value to be specified as in other widgets. Not sure why it is missing in this widget.

**Comment by fazlan-nazeem** [comment]
all pie charts which have an associated table in the bottom of it will have this problem when we increase the limit to a large number.
