### ISSUE TITLE
Faults tab in Analytics Publisher Dashboard is not working.

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/analytics-apim#1086]
**Description:**
Faults tab in the analytics publisher node is not showing anything. In the overview, it is shown that there are 5 throttle out requests which is correct according to my testing scenario.

But when I navigated to the faults tab, it shows nothing.
When I inspected it, the following error was shown in the console tab.

<img width="901" alt="Screen Shot 2020-03-22 at 5 48 28 PM" src="https://user-images.githubusercontent.com/17596317/77249884-36350900-6c6a-11ea-82bf-63840dd51c6d.png">

**Suggested Labels:**
Bug, Affected/3.1.0-rc3

**Suggested Assignees:**

**Affected Product Version:**
3.1.0-rc3

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Start analytics node and send some throttle out events to analytics node. Go to faults tab.

**Related Issues:**

**Comment by RAVEENSR** [comment]
And also Devices tab is also not working and the same error can be seen in the console panel.

**Comment by RAVEENSR** [comment]
Fixed with https://github.com/wso2/analytics-apim/pull/1087
