### ISSUE TITLE
Limit dropdown value in developer dashboard automatically get updated when that is set to 0 and autosync is turned on

### ISSUE THREAD

**Issue by Ketharan** [wso2/analytics-apim#1090]
**Description:**
Limit drop-down value of the following widgets in the developer dashboard automatically gets updated to 5 when that is set to 0 and  the date time range is synced.
    APIM Faulty per app
    APIM Top app users
    APIM application api usage
    APIM app resource usage

**Suggested Labels:**
APIM-3.1.0-RC4, Type/Improvement

**Affected Product Version:**
3.1.0-RC4

**OS, DB, other environment details and versions:**    
Firefox (74.0), Ubuntu

**Steps to reproduce:**
1. Set the limit value of one of the mentioned widget to 0
2. Turn on the sync feature in the date time range widget
3. Wait for the real time update

**Comment by ruwiniwj** [comment]
Fixed with https://github.com/wso2/analytics-apim/pull/1104
