### ISSUE TITLE
Some data being listed even though the limit value is set to 0 in Top app creator widget

### ISSUE THREAD

**Issue by Ketharan** [wso2/analytics-apim#1092]
**Description:**
Even though the limit value is set to 0 in Top App Creators widget, it shows the available data.

**Suggested Labels:**
APIM-RC-4, Type/Bug

**Affected Product Version:**
APIM-RC-4

**OS, DB, other environment details and versions:**    
Firefox (74.0), Ubuntu
 
**Steps to reproduce:**
Set the limit value in Top app creator widget to 0 and the data will be listed if available.

**Comment by ruwiniwj** [comment]
Fixed with https://github.com/wso2/analytics-apim/pull/1104
