### ISSUE TITLE
Limit value changes to default value of 5, when reloading the page for Top App Creator widget.

### ISSUE THREAD

**Issue by Ketharan** [wso2/analytics-apim#1093]
**Description:**
The limit value of the drop-down of Top App Creator widget changes to default 5 when reloading the page. Does not happen with some other widgets. Though the value changes to 5, the number of listings remains same as the previous count. 

**Suggested Labels:**
APIM-3.1.0-RC-4, Type/Bug

**Affected Product Version:**
3.1.0-RC-4

**OS, DB, other environment details and versions:**    
Firefox (74.0), Ubuntu

**Steps to reproduce:**
Set the limit drop-down value to non other than five.
Reload the browser window.

**Comment by ruwiniwj** [comment]
Fixed with https://github.com/wso2/analytics-apim/pull/1104
