### ISSUE TITLE
GDPR for Analytics

### ISSUE THREAD

**Issue by TanyaM** [wso2/analytics-apim#1096]
**Description:**
The content of the current doc [1] is outdated. It has information on removing PII references when the APIM Analytics is backed by DAS and not by SP. I checked APIM 2.6.0 docs and the content there too is incorrect. 

We can follow an approach like below to support GDPR.
One part of the solution is to provide a siddhi application to delete or obfuscate PII references[2]. As we have a defined set of siddhi applications in APIM Analytics and we know where there are PII references, we should be able to provide this siddhi application by ourselves rather than asking customers to write this application.

The other part of the solution is to remove PII references from relational databases using an SQL approach as described in [3]

[1] https://apim.docs.wso2.com/en/latest/Administer/ProductSecurity/general-data-protection-regulation-gdpr-for-wso2-api-manager/#running-the-tool-in-api-manager-analyticso
[2] https://docs.wso2.com/display/SP440/Creating+GDPR+Compliant+Siddhi+Applications
[3] https://docs.wso2.com/display/ADMIN44x/Extending+the+Identity+Anonymization+Tool

**Affected Product Version:**
3.1.0

**Comment by RAVEENSR** [comment]
The fix(#1107) for this issue is tested in the following database with respect to the stated db versions.

DB Type | Version 
-- | -- 
H2 | 1.2.140
MySQL | 8
MsSQL | 2017
PostgreSQL | 10.5
DB2 | 11.5
