### ISSUE TITLE
No mention of health check URL for analytics 3.0.0 dashboard containers in documentation

### ISSUE THREAD

**Issue by kalevivek11** [wso2/analytics-apim#1097]
Hi,
we have done dockerized distributed deployment for apim 3.0 and apim analytics but our dashboard containers are getting restarted regularly as there are no health check url metion in your documentation, we for other components health check urls they are mentioned in your documentation which is available online.

**Comment by Ketharan** [comment]
Hi,
Thanks for reporting the issue. Now we have updated the docs to include the health check information.
You can find that information here.
https://apim.docs.wso2.com/en/latest/install-and-setup/installation-guide/basic-health-checks/
