### ISSUE TITLE
analytics 3.0.0 dashboard logout issue

### ISSUE THREAD

**Issue by kalevivek11** [wso2/analytics-apim#1102]
I am able to load analytics dashboard
but on click of logout, we are getting error as the site cant be reached.

I have attached my YAML
[deployment - Copy.zip](https://github.com/wso2/analytics-apim/files/4413164/deployment.-.Copy.zip)
![image](https://user-images.githubusercontent.com/10954248/78106049-34103e80-7410-11ea-8ff4-cb27993ae7b0.png)
![dashboardLogout](https://user-images.githubusercontent.com/10954248/78106127-6457dd00-7410-11ea-8991-51749409137a.JPG)

 file and error screenshot.

please correct me in my configuration

**Comment by RAVEENSR** [comment]
Define the `externalLogoutUrl` property under `auth.configs` in the dashboard deployment.yaml file. Please refer the documentation for more https://apim.docs.wso2.com/en/latest/learn/analytics/configuring-apim-analytics/#details-of-the-properties-in-apim-idp-client

**Comment by ruks** [comment]
Closing the issue since answered.
