### ISSUE TITLE
wso2 apim analytics 3.0.0 dashboard -> developer portal details

### ISSUE THREAD

**Issue by kalevivek11** [wso2/analytics-apim#1103]
i have done analytics setup -> logged in as admin

in dashboard -> developer portal details -> i can see application created by admin not of other users

![image](https://user-images.githubusercontent.com/10954248/78108409-f530b780-7414-11ea-9746-be7c14508398.png)

**Comment by ruwiniwj** [comment]
The developer portal dashboard only shows stats for applications visible to the logged in user. This only includes the applications created by the logged in user and the applications shared with the logged in user. This is not a bug, it is the expected behaviour.

**Comment by kalevivek11** [comment]
@ruwiniwj don't you think the admin should be able to see every user's detail?

**Comment by ruwiniwj** [comment]
If a user logins to the APIM developer portal he can only access his applications and applications shared with him. Even an admin can only view the applications he has access. Similarly in analytics, the developer portal dashboard only show the stats for the applications accessible to the logged in user.

**Comment by kalevivek11** [comment]
@ruwiniwj how to enable application sharing with admin only

**Comment by ruwiniwj** [comment]
Application sharing  enables users to share their applications and subscriptions with a specific logical group/groups such as an organization.  Please refer the documentation[1] for more details.

[1]. https://apim.docs.wso2.com/en/latest/learn/consume-api/manage-application/sharing-applications/sharing-applications/
