### ISSUE TITLE
bot detection email not getting generated

### ISSUE THREAD

**Issue by kalevivek11** [wso2/analytics-apim#1110]
i have followed below steps:
1. followed the link:
https://apim.docs.wso2.com/en/latest/learn/api-security/threat-protection/bot-detection/

2. did all configuration as mentioned by document 

3. but getting below error in worker logs

![image](https://user-images.githubusercontent.com/10954248/79455899-362aed80-800b-11ea-912b-2a0e70608d5a.png)

please provide proper steps here.

**Comment by fazlan-nazeem** [comment]
We have checked this and was unable to reproduce such an issue.
