### ISSUE TITLE
Track changes from APIM Analytics 3.1.0 to APIM 3.2.0

### ISSUE THREAD

**Issue by ruwiniwj** [wso2/analytics-apim#1113]
**Description:**
Track changes from APIM analytics 3.1.0 to 3.2.0.

**Comment by ruwiniwj** [comment]
- Supporting monitoring dashboard in analytics (https://github.com/wso2/analytics-apim/issues/1147) 
- Reorganize analytics dashboards (https://github.com/wso2/analytics-apim/issues/1144)
- Support CSV and PDF download (https://github.com/wso2/analytics-apim/issues/1151)
- Redefine analytics scopes (https://github.com/wso2/analytics-apim/issues/1127)
- GDPR for Analytics (https://github.com/wso2/analytics-apim/issues/1096)

**Comment by ruwiniwj** [comment]
Move API availability and Alert history stats from admin portal to monitoring dashboard(https://github.com/wso2/analytics-apim/issues/1152)

**Comment by ruks** [comment]
Closing this since 3.2.0 is released.
