### ISSUE TITLE
Track DB changes/migrations for APIM Analytics-3.2.0

### ISSUE THREAD

**Issue by RAVEENSR** [wso2/analytics-apim#1118]
**Description:**
This issue is created to track all the Db related changes/migrations done for the APIM Analytics 3.2.0 release.

**Comment by RAVEENSR** [comment]
Adding `apiName` column to `ApimAllAlert` table via https://github.com/wso2/analytics-apim/pull/1121.

This schema change will not impact migrations as we don't usually migrate alerts data as they have no historical value.

**Comment by ruks** [comment]
As a performance improvement and support exact match, graphQL operations need to be updated by sorting alphabetical order. This needs to be done in all the aggregated tables which contain the resource template column. @Krishanx92 FYI

**Comment by ruks** [comment]
Closing this since 3.2.0 is released.
