### ISSUE TITLE
Make widget header/title configurable

### ISSUE THREAD

**Issue by ruwiniwj** [wso2/analytics-apim#1124]
**Description:**
Currently the widget header is defined by the property _name_ in the _widget.config_ file as follows. 

```
{
  "name": "APIM Api Availability",
  "id": "APIMApiAvailability",
  "thumbnailURL": "",
  "configs": {
    ...,
    "options": [
      {
        "id": "header",
        "title": "Header",
        "type": {
          "name": "BOOLEAN",
          "possibleValues": [
            true,
            false
          ]
        },
        "defaultValue": true
      },
    }
}
```

Displaying the widget header for all the widgets in a dashboard will take up unnecessary space. However, we are unable to remove the header using the _options_ config for _header_ because the widget export feature is embedded in the header, and  removing the header will result in removing the widget export feature for that widget. A solution to this is to make the widget header/title configurable and to provide an empty string for the widget header when it does not need to be displayed.

**Comment by ruwiniwj** [comment]
The _options_ config for providing the widget title is as follows:
 ```
     {
        "id": "headerTitle",
        "title": "Overall Api Info",
        "type": {
          "name": "TEXT",
        },
        "defaultValue": "Title1"
      }
```

**Comment by TanyaM** [comment]
By default golden layout doesn't allow giving an empty string in the widget configuration for the widget title and if we provide an empty string it uses the default react component name "lm-react-component".
Hence we need to do a fix in carbon-dashboards side [1] to support empty strings for titles.

[1] https://github.com/wso2/carbon-dashboards/blob/master/components/dashboards-web-component/src/viewer/components/DashboardRenderer.jsx#L138-L147

**Comment by ruwiniwj** [comment]
Reopening since the carbon-dashboard fix has not been implemented yet.

**Comment by Ketharan** [comment]
The same can be achieved by providing a space char (' ') instead of an empty string in the dashboard JSON files. Since we can achieve this from our side, better not to change the empty string check unless really needed.

**Comment by ruwiniwj** [comment]
The widget header has been removed from the dashboards with https://github.com/wso2/analytics-apim/pull/1408. Hence closing this issue.
