### ISSUE TITLE
Victory charts are used for bar charts instead of VizG charts

### ISSUE THREAD

**Issue by TanyaM** [wso2/analytics-apim#1130]
**Description:**
Victory bar charts are used for following bar chart widgets in PR [1] and we need to change those to VizG charts for consistency and better styling.

Average Api Latency
Total Api Traffic

[1] https://github.com/wso2/analytics-apim/pull/929

**Comment by ruks** [comment]
Since those widgets are refactored and used the victory for deeper customization. Hence will close and consider in the future if further styling issues noticed.
