### ISSUE TITLE
"No Data Available" error messages needs to be consistent in styling

### ISSUE THREAD

**Issue by TanyaM** [wso2/analytics-apim#1131]
**Description:**
Some widgets have different syling in "No Data Available" messages and those need to be make consistent across all widgets. 

Correct styling of the "No Data Available" message
<img width="600" alt="correct" src="https://user-images.githubusercontent.com/3957104/81361154-41010b80-90fb-11ea-8da2-1fa6f87bd4da.png">

Inconsistent styling
<img width="238" alt="incorrect" src="https://user-images.githubusercontent.com/3957104/81361179-50805480-90fb-11ea-9fa6-f18df8b20ed3.png">

Example widget this can be observed in is "API Error Analysis" widget.

**Comment by TanyaM** [comment]
Fixed for following widgets.

- Api Error Analysis
- Api Resource Traffic
- Api Error Percentages
- Average Api Latency
- Overall Highest Latency

Need to fix in 'Total Api Traffic' widget

**Comment by pahans** [comment]
this is fixed in latest master
