### ISSUE TITLE
API Analytics page stuck show only blue screen no login page any issue.

### ISSUE THREAD

**Issue by gadeykarthik** [wso2/analytics-apim#1146]
**Description:**
I have settuped the API manager as quick setuped all the services are running but analatyics server is not working

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
3.1.0

**OS, DB, other environment details and versions:**    
linux default db
**Steps to reproduce:**
![image](https://user-images.githubusercontent.com/35322091/83539216-66274500-a514-11ea-9557-c697a6b0dbfc.png)

**Related Issues:**

 AM_SYSTEM_APPS does not exists in the AM_DB database.

**Comment by ruwiniwj** [comment]
This is due to the AM_DB not being properly configured. Please refer https://apim.docs.wso2.com/en/latest/learn/analytics/configuring-apim-analytics/#step-4-configure-databases.

**Comment by vsai9594** [comment]
> **Description:**
> I have settuped the API manager as quick setuped all the services are running but analatyics server is not working
> 
> **Suggested Labels:**
> 
> **Suggested Assignees:**
> 
> **Affected Product Version:**
> 3.1.0
> 
> **OS, DB, other environment details and versions:**
> linux default db
> **Steps to reproduce:**
> ![image](https://user-images.githubusercontent.com/35322091/83539216-66274500-a514-11ea-9557-c697a6b0dbfc.png)
> 
> **Related Issues:**
> 
> AM_SYSTEM_APPS does not exists in the AM_DB database.

did u solve this ? i am also facing the same issue

**Comment by ruwiniwj** [comment]
@vsai9594 as i mentioned before this is due to the AM_DB not being properly configured. Please refer https://apim.docs.wso2.com/en/latest/learn/analytics/configuring-apim-analytics/#step-4-configure-databases on how the AM_DB needs to be configured. Else moving both the APiM pack and the Analytics pack to the same aprent directory will a

**Comment by vsai9594** [comment]
i have both API manager (3.1.0) folder and analytics folder in the same parent folder
ApiManager(parent folder)
------3.1.0
------wso2-analytics

this is how my directory structure looks.


can you please be specific on what i should. i have been stuck on this from 2 days

**Comment by ruwiniwj** [comment]
Configure the AM_DB as mentioned in https://apim.docs.wso2.com/en/latest/learn/analytics/configuring-apim-analytics/#step-4-configure-databases. This issue occurs when the AM_DB is not correctly configured in Analytics and therefore the analytics server is unable to establish the connection to the AM_DB during login.

**Comment by vsai9594** [comment]
> Configure the AM_DB as mentioned in https://apim.docs.wso2.com/en/latest/learn/analytics/configuring-apim-analytics/#step-4-configure-databases. This issue occurs when the AM_DB is not correctly configured in Analytics and therefore the analytics server is unable to establish the connection to the AM_DB during login.

i tried that and then its working and also i am not using sql db
