### ISSUE TITLE
The API selection of latency widgets becomes empty after a while

### ISSUE THREAD

**Issue by ruwiniwj** [wso2/analytics-apim#1186]
**Description:**
The API selection of latency widgets becomes empty after a while

<img width="1635" alt="Screenshot 2020-06-11 at 19 16 29" src="https://user-images.githubusercontent.com/20040505/84392610-35cc5e80-ac18-11ea-9a87-452dcd6d0f23.png">
<img width="1585" alt="Screenshot 2020-06-11 at 19 16 22" src="https://user-images.githubusercontent.com/20040505/84392628-395fe580-ac18-11ea-873c-aae9bc367cba.png">

**Comment by ruks** [comment]
This is fixed with adding multi-selector. Hence closing
