### ISSUE TITLE
Change the context contains condition used to filter APIs from AM_API table

### ISSUE THREAD

**Issue by ruwiniwj** [wso2/analytics-apim#1191]
**Description:**
Currently when retrieving API list from AM_API table, we use a string contains function on the 
 CONTEXT field to check whether the API belongs to the users tenant[1]. However, since the string contains function only check whether the tenant name exists as a substring of the CONTEXT this will result in retrieving APIs of another tenant in the edge case where the searched tenant name exists as a substring of the API context. This can be avoided by using CONTEXT_TEMPLATE column instead of CONTEXT column to filter APIs.

[1]. https://github.com/wso2/carbon-dashboards/pull/1189/files#diff-ecdbe390bcc94cfd108b5c3f49d24ef0R78

**Comment by ruks** [comment]
I was not able to reproduce, Can you please mention the affected widgets?

**Comment by ruwiniwj** [comment]
Closing since SP based analytics is deprecated
