### ISSUE TITLE
Fix styling of resource list in API Latency Time widget

### ISSUE THREAD

**Issue by ruwiniwj** [wso2/analytics-apim#1214]
**Description:**
In API Latency Time widget if there are a larger number of resources in the API, the resource listing will be too long. We can avoid this by either adding a scroll or an autocomplete.

**Comment by ruks** [comment]
This is fixed now. Hence closing.

![image](https://user-images.githubusercontent.com/1345278/87401616-fce92600-c5d7-11ea-9dfe-4ce203185f2d.png)
