### ISSUE TITLE
generate report button not required for "APIM Monthly API Usage Report" widget

### ISSUE THREAD

**Issue by ruks** [wso2/analytics-apim#1241]
"APIM Monthly API Usage Report" widget in admin dashboard used to create reports. So having a generate report button doesn't add any value.

**Comment by fazlan-nazeem** [comment]
I don't see a button as such in this widget. 

<img width="956" alt="Screenshot 2020-07-16 at 13 40 36" src="https://user-images.githubusercontent.com/13759167/87644607-f8547700-c769-11ea-9a27-d857f3d7390c.png">

**Comment by Ketharan** [comment]
I think here the pdf export button in the header need to be removed. Considering the usage of this widget, we can remove the header itself as the maximize option also not necessary for this one.
