### ISSUE TITLE
Widget timestamp is not represent in browser time zone

### ISSUE THREAD

**Issue by ruks** [wso2/analytics-apim#1246]
**Description:**
Widgets in the dashboards should represent the time in the client or browser timezone. ATM most of the widget represents it in gateway timezone. This needs to be fixed when fetching and rendering.

**Comment by TanyaM** [comment]
Noticed that widgets in Business Analytics dashboard sometimes display a default timestamp regardless of the actual timestamp.

**Comment by ruks** [comment]
Closing the issue since SP analytics is deprecated.
