### ISSUE TITLE
Legend's tooltips are shortened in manager dashboard

### ISSUE THREAD

**Issue by ruks** [wso2/analytics-apim#1247]
**Description:**
When the API names are shortened its
<img width="180" alt="Screenshot 2020-06-29 at 11 54 27" src="https://user-images.githubusercontent.com/1345278/85980297-bc967f00-b9ff-11ea-9066-cc2ad04729b9.png">
 the tooltip also gets shortened. But tooltip should show the complete text.  

Need to fix in followings, 
* TOP 10 API USAGE DURING PAST 30 DAYS
* TOP 10 API PERFORMANCE DURING PAST 30 DAYS

**Comment by Ketharan** [comment]
Seems this works as expected initially and the shortening happens after hovering over the table. The following issue in victory might caused this.
https://github.com/FormidableLabs/victory/issues/778
Upgrading the victory version in via Grammer might solve the issue.

**Comment by ruks** [comment]
Closing the issue since SP analytics is deprecated.
