### ISSUE TITLE
Show floating-point numbers in the y-axis even it represents counting numbers.

### ISSUE THREAD

**Issue by ruks** [wso2/analytics-apim#1248]
**Description:**

Manager Analytics dashboard show floating-point numbers in the y-axis even it represents counting numbers.

Need to fix in,
* TOP 10 THROTTLED OUT APIS DURING PAST 30 DAYS
* ERRORS DURING PAST 30 DAYS
* API USAGE OVER TIME
* PERFORMANCE SUMMARY 
* API THROTTLED OUT REQUESTS OVER TIME
* API ERRORS OVER TIME
* APIS CREATED OVER TIME
* SUBSCRIPTIONS OVER TIME
* APPLICATIONS CREATED OVER TIME
* DEVELOPER SIGNUPS OVER TIME

![image](https://user-images.githubusercontent.com/1345278/85981036-1b102d00-ba01-11ea-8429-54ab6d7da367.png)

**Comment by fazlan-nazeem** [comment]
we also need to limit the decimal points.

**Comment by ruks** [comment]
duplicate https://github.com/wso2/analytics-apim/issues/1300
