### ISSUE TITLE
No legends for "ERRORS DURING PAST 30 DAYS" widget

### ISSUE THREAD

**Issue by ruks** [wso2/analytics-apim#1249]
**Description:**
No legends for "ERRORS DURING PAST 30 DAYS" widget in manager analytics.

**Comment by Ketharan** [comment]
Since the errors are the count across all the APIs seems we don't need a legend for this widget. (We don't have any information to show in the legend). 
@ruks is that points to the label for the y axis? If that is the case that is fixed with https://github.com/wso2/analytics-apim/pull/1338

**Comment by fazlan-nazeem** [comment]
Yes, as @Ketharan pointed out, this chart plots the aggregate error count with respect to the time. So we don't need labels.
