### ISSUE TITLE
"API USAGE OVER TIME" show empty data 

### ISSUE THREAD

**Issue by ruks** [wso2/analytics-apim#1253]
"API USAGE OVER TIME" Widget show 0 API invocation when non subscribed application is selected. ideally it should not show any data. 

Dashboard: Manager Analytics
Page: API Usage

![image](https://user-images.githubusercontent.com/1345278/86001719-ed40dd80-ba2c-11ea-9d1f-cbd2702d3c17.png)

**Comment by fazlan-nazeem** [comment]
Since the data plotted is accurate, we will not be changing this behavior.
