### ISSUE TITLE
Click on Check box redirect to another widget before render changes.

### ISSUE THREAD

**Issue by ruks** [wso2/analytics-apim#1254]
Click on Check redirect to another widget before render changes.

Dashboard: Manager Analytics
Page: API Usage
Widget: OVERALL API USAGE

![image](https://user-images.githubusercontent.com/1345278/86002163-9982c400-ba2d-11ea-8c46-06ce7c35813d.png)

**Comment by ruwiniwj** [comment]
The tick box functionality has been removed with https://github.com/wso2/analytics-apim/issues/1309. Hence closing this ticket.
