### ISSUE TITLE
Y axis legends and informations are missing

### ISSUE THREAD

**Issue by ruks** [wso2/analytics-apim#1257]
Dashboard: Manager Analytics
Page: Performance Summary
Widget: PERFORMANCE SUMMARY and THROTTLE SUMMARY

It is not clear what is the parameters used to show performance summary. Better to show legends in y-axis then. 

Similar for "THROTTLE SUMMARY" and better to have a y axis label with "hits"

**Comment by Ketharan** [comment]
Following widgets have this issue
page/widgetId
Business Analytics/ApiUsageOverTime
Business Analytics/APIMApiLatencySummary
Business Analytics/Top10ApiPerformanceOverTime
Business Analytics/OverallFaultAnalytics
Business Analytics/Top10ThrottledApisOverTime
Business Analytics/Top10ApiUsageOverTime
Monitoring/APILatencyOverTime
API Analytics/APIMApiLatencyTime
API Analytics/ApiUsageOverTime

**Comment by Ketharan** [comment]
As shown in the following images some widgets have the horizontal label on top of the axis and others have vertical labels along the axis. Shall we have a consistent labeling here? Also, the vizgrammar chats seems do not support vertical labeling. 

![horizontal](https://user-images.githubusercontent.com/25489203/87323973-198c4c00-c54d-11ea-8a13-37db7b657163.png)

![vertical](https://user-images.githubusercontent.com/25489203/87324000-227d1d80-c54d-11ea-8a8a-744fb41e6146.png)

**Comment by ruks** [comment]
duplicate https://github.com/wso2/analytics-apim/issues/1299
