### ISSUE TITLE
API Latency Over Time Chart in Monitoring Dashboard doesn't correctly stack lines

### ISSUE THREAD

**Issue by jaadds** [wso2/analytics-apim#1264]
**Description:**
API Latency Over Time chart is a stacked line chart. But when selecting certain time periods and time scales, the lines overlap without stacking on top of one another. 

**Affected Product Version:**
3.2.0-Alpha

**OS, DB, other environment details and versions:**    
Was observed in Distributed Setup

**Steps to reproduce:**
In the Distributed setup go to Latency Page and Select the API Latency Summary and click on it and follow the navigation. Upon clicking the focus will be set to API Latency Over Time. Now from the Date Range Picker select 1 Hour as the Quick Time Range and minutes as the Granularity Mode.

![Selection_031](https://user-images.githubusercontent.com/9979804/86244073-054b6500-bbc5-11ea-9c6b-ba389364919b.png)

**Comment by Ketharan** [comment]
Seems like this is not a stacked line chart rather a normal line chart. Hence overlapping/crossing is fine.

**Comment by ruks** [comment]
@Ketharan we did some changes to the chart right? now is it like a stacked chart?

**Comment by Ketharan** [comment]
We did changes to the latency summary widget, which is a stacked bar chart. But this one is a line chart and not a stacked one. That's why here we have overlappings and crossings. If we need this to be a stacked line chart we can change this so applying the changes of the latency summary widget as well.

**Comment by ruks** [comment]
@Ketharan shall we make this stacked line chart? Will calculate other latency as we calculate in the latency summary widget.

**Comment by Ketharan** [comment]
Yes. Will send a PR changing this to a stacked line chart.
