### ISSUE TITLE
[Api Traffic Summary Widget]  X-axis ticks need to be rotated from corner instead of rotating at center

### ISSUE THREAD

**Issue by TanyaM** [wso2/analytics-apim#1285]
**Description:**
Please see the screenshot below. Ticks need to be rotated from the corner, unless the part above x-axis will get covered when there is more data.

<img width="824" alt="ticks" src="https://user-images.githubusercontent.com/3957104/86429628-c2e16f80-bd0d-11ea-81f3-bb821ca15056.png">

**Comment by ruks** [comment]
This is fixed now 
![image](https://user-images.githubusercontent.com/1345278/88254638-8208c500-ccd3-11ea-8372-c82df563e3ed.png)
