### ISSUE TITLE
[Monitoring] Version Selector under API Latency Over Time widget lists the APIs instead of Versions

### ISSUE THREAD

**Issue by jaadds** [wso2/analytics-apim#1292]
**Description:**
Version selector shows API Names instead of Versions
<img width="1142" alt="error_in_version_selector" src="https://user-images.githubusercontent.com/9979804/86442318-3cd42180-bd2b-11ea-9950-5441122be3ca.png">

**Comment by ruks** [comment]
There was a refactoring for filter attributes and use muti selector instead of standard material UI select. It is not reproducible now and hence closing.
![image](https://user-images.githubusercontent.com/1345278/87005613-e65c5c80-c1dc-11ea-92a5-00b6258f4e60.png)
