### ISSUE TITLE
[Business Analytics] [TOP 10 API USAGE FOR MONTH] Y-axis ticks for request count are displayed to several decimal points

### ISSUE THREAD

**Issue by TanyaM** [wso2/analytics-apim#1300]
**Description:**
 
Please see the screenshot below.
Y-axis ticks are displayed for several decimal points which is meaningless since request count doesn't have decimal points.

<img width="622" alt="decimal" src="https://user-images.githubusercontent.com/3957104/86582791-db68b880-bf9f-11ea-9cfb-34ae0323f318.png">

**Comment by Ketharan** [comment]
This is observable in almost every overtime plots, especially when there are a low number of data points. Need to check other occurrences as well.

**Comment by TanyaM** [comment]
This is observable in some of the other widgets too.
Ex: Top 10 Throttled Out Apis Over Time

**Comment by Ketharan** [comment]
This is observable in the following widgets as well
dashboard/widgetid
Business Analytics/APIMSignupsAnalytics
Business Analytics/ApiUsageOverTime
Business Analytics/APIMApiCreatedAnalytics
Business Analytics/PerformanceSummary
Business Analytics/ApiThrottleAnalytics
Business Analytics/APIMApiLatencyTime
Business Analytics/APIMOverallApiUsage
Business Analytics/APIMAppCreatedAnalytics
Business Analytics/ThrottleSummary
Business Analytics/ApiFaultAnalytics
Business Analytics/APIMSubscriptionsAnalytics
API Analytics/ApiThrottleAnalytics
API Analytics/APIMOverallApiUsage
API Analytics/ApiFaultAnalytics
API Analytics/ApiUsageOverTime
