### ISSUE TITLE
Seems some widgets don't need a limit selector

### ISSUE THREAD

**Issue by Ketharan** [wso2/analytics-apim#1304]
**Description:**
Some over-time widgets don't have a table corresponding to the time-series data plot. Hence the limit selector is not needed.
Monitoring/error summary over time
Monitoring/API latency over time
Monitoring/API traffic over time

**Suggested Labels:**
Type/Improvement, Priority/Normal

**Affected Product Version:**
3.2.0-alpha

**Comment by ruwiniwj** [comment]
The limit selector is not used limit the number of entires in the table but rather to limit the number of data entries retrieved from the backend. Removing this may result in a large data load being retrieved at once which could cause memory outage. Hence closing this issue.
