### ISSUE TITLE
[Business Analytics] [API Backend Usage Summary] Alignment issues in the table

### ISSUE THREAD

**Issue by TanyaM** [wso2/analytics-apim#1310]
**Description:**
Please see the screenshot below.
<img width="1230" alt="alignment" src="https://user-images.githubusercontent.com/3957104/86595217-04944380-bfb6-11ea-8325-7ab3cec1c9ae.png">

**Comment by ruks** [comment]
Noticed this in multiple tables. So need to review all the tables for a similar issue.
