### ISSUE TITLE
API Latency over time widget date format seems to be wrong

### ISSUE THREAD

**Issue by fazlan-nazeem** [wso2/analytics-apim#1329]
**Description:**
 see the image below.

<img width="677" alt="Screenshot 2020-07-13 at 15 46 38" src="https://user-images.githubusercontent.com/13759167/87293943-a836a400-c520-11ea-8bc8-e1c6f540011d.png">

Furthermore, it seems like the ordering of the data points is not in the correct order. The latest timestamp is plotted on the left.

**Comment by pahans** [comment]
This is fixed in the latest master
![image](https://user-images.githubusercontent.com/1552869/88146896-1b73a080-cc1a-11ea-8301-9f2445f7257d.png)
