### ISSUE TITLE
WSO2 API-M Analytics Dashboard Creating Custom Widget

### ISSUE THREAD

**Issue by BurakKarayel** [wso2/analytics-apim#1345]
When I try to create custom widget using analytics dashboard after entering widget name and pressing next, page become irresponsive. 

![image](https://user-images.githubusercontent.com/64360783/87674244-699e2500-c77e-11ea-8c7c-690c537e6bf2.png)

Steps to produce:

- Press Create Widget icon
- Enter widget name and hit Next button

**Comment by ruks** [comment]
@BurakKarayel thanks for reporting the issue. But can you please mention the analytics version you are using?

**Comment by BurakKarayel** [comment]
@ruks thanks for the response. Analytics version is 3.0.0

**Comment by ruks** [comment]
@BurakKarayel APIM 300 we didn't support custom widget generation. Also wanted to remove UI support later. From 3.1.0 onwards, it supports a tool[1] to generate custom widgets.

[1] https://apim.docs.wso2.com/en/next/learn/analytics/creating-custom-widgets-in-analytics-dashboards/

**Comment by BurakKarayel** [comment]
@ruks Does 3.1.0 support creating custom widget by using Analytics Dashboard UI or as mentioned in the link do we need to write reactJs code?

**Comment by ruks** [comment]
3.1.0 also support custom widget with the provided tool and react as mention in this doc[1]

[1] https://apim.docs.wso2.com/en/latest/learn/analytics/creating-custom-widgets-in-analytics-dashboards/#!

**Comment by BurakKarayel** [comment]
@ruks Is it possible to  use API-Manager 3.0.0 version with APIM Analytics 3.1.0 version? Are there any compatibility issues?

**Comment by ruks** [comment]
No Both APIM and analytics should be same version. But widgets generated in 3.1.0 should work with 3.0.0. Since it is a react app it should work and in case any issue, we can edit it and make it work.

**Comment by BurakKarayel** [comment]
@ruks thanks for the response.

**Comment by ruks** [comment]
> @ruks thanks for the response.

I'll close this issue since 300 doesn't support UI Baed wizard to generate widgets. If you face any issues in the above-mentioned tool, please open another git issue.
