### ISSUE TITLE
User and Role not synced during outbound provisioning while created offline

### ISSUE THREAD

**Issue by soniavarshney** [wso2/analytics-apim#1349]
Hi Team 

I setup two wso2 identity server 5.10. It wso2-is-1 have store1 and another wso2-is-2 have store2. I configured both user store for outbound provisioning. Its working fine. Now when I stop the store2 server and create some users and group in store1 now I up the store2 server but those users and group which i created while store 2 was down not got synced in store2. How we can do ? second thing when any store1's user update his password how it will synced in store 2 server?

**Comment by fazlan-nazeem** [comment]
Please report Identity Server issues in https://github.com/wso2/product-is/issues. This repo is for reporting issues for wso2 apim analytics.
