### ISSUE TITLE
Error when loading widget - timeout of 2000ms exceeded

### ISSUE THREAD

**Issue by maron546** [wso2/analytics-apim#1369]
**Description:**
The first time we try to load the dashboards on the analytics-dashboard application, widgets are unable to fetch data (see the attached picture). The second time, data are displayed correctly.
This behavior seems to be caused by timeout in fetching data, for example:
*Error occurred when loading widget 'APIMFaultyPerApp'. Error: timeout of 2000ms exceeded*
Is there any way to increase or remove this timeout or any other solution?

![88062156-bad85b00-cb68-11ea-8332-4772595a1a6e](https://user-images.githubusercontent.com/68596720/88069263-887f2b80-cb71-11ea-930d-a81ec1474b9c.png)

**Affected Product Version:**
3.1.0

**OS, DB, other environment details and versions:**   
Rancher 19.03.5
PostgreSQL 11

**Comment by ruwiniwj** [comment]
This could be due to the backend call to retrieve widget content failing due to a network slowness.

**Comment by maron546** [comment]
But this happens just the first time we try to load the dashboard, for few minutes after a restart. All the following attemps are able to retrieve data.

**Comment by RAVEENSR** [comment]
Fixed with https://github.com/wso2/carbon-dashboards/pull/1244
