### ISSUE TITLE
API LATENCY OVER TIME widget in Monitoring Dashboard does not work when an API is selected

### ISSUE THREAD

**Issue by RAVEENSR** [wso2/analytics-apim#1383]
**Description:**
API LATENCY OVER TIME widget in Monitoring Dashboard does not work when an API is selected. It does not render any graph and does not render the selection panel for the API version and the resource.

<img width="1649" alt="latencyerror" src="https://user-images.githubusercontent.com/19996612/88177901-2f81c700-cc47-11ea-8717-0a883263989b.png">

It works when clicks the bar in the API LATENCY SUMMARY widget(via drill down). But still it does not render the API version and the API resource selection panels.

**OS, DB, other environment details and versions:**    
APIM Analytics 3.2.0-beta
Oracle 19.3c

**Steps to reproduce:**
Invoke and API from the DEevPortal and select that API from the drop-down in the API LATENCY OVER TIME widget in the Monitoring Dashboard.

**Comment by Ketharan** [comment]
Here the API LATENCY OVER TIME widget only provides the information in resource level granularity. Hence selecting only the API will not render the graph. Hence that part seems expected.
But the later part which the version and resource selection panel is not reproducible. When selecting the API the version selection panel renders and selecting the version renders the resource selection panel.

**Comment by RAVEENSR** [comment]
> Here the API LATENCY OVER TIME widget only provides the information in resource level granularity. Hence selecting only the API will not render the graph. Hence that part seems expected.
Yes, that is correct.  I meant to say we only have the option to select the API name. Others are not showing.
> But the later part which the version and resource selection panel is not reproducible. When selecting the API the version selection panel renders and selecting the version renders the resource selection panel.
This can be reproduced in oracle 19.3c
