### ISSUE TITLE
Monitoring dashboard not honour the sync button in day time picker 

### ISSUE THREAD

**Issue by ruks** [wso2/analytics-apim#1388]
Widget refreshing even sync button not enabled, in the Monitoring dashboard

**Comment by Ketharan** [comment]
This need fixes for the following widget
APIMOverallApiInfo
ErrorByAppAndAPI
AppAndAPIErrorTable
AppAndAPIErrorsByTime
APILatencySummary
APILatencyOverTime
APITrafficSummary
APITrafficOverTime
APIMApiAvailability
ApiAvailability
APIMAlertSummaryByAPIs
APIMAlertSummary
