### ISSUE TITLE
[Monitoring dashboard] Initial rendering of widgets shows all APIs but the filter label is blank

### ISSUE THREAD

**Issue by Ketharan** [wso2/analytics-apim#1396]
**Description:**
Traffic and Latency page widgets in monitoring dashboard show statistics for all APIs (with the applied limit value) but the filter selection text don't have any label. Better to provide the 'all' label there.
![missing_label](https://user-images.githubusercontent.com/25489203/88263061-057fe180-cce7-11ea-9220-19aff1a3beba.jpg)

**Suggested Labels:**
Type/Improvement, Priority/High

**Affected Product Version:**
3.2.0-beta

**Comment by ruks** [comment]
Fixed with https://github.com/wso2/analytics-apim/pull/1417
