### ISSUE TITLE
Analytics Dashboard Widget Timeout Exceeding before loading data.

### ISSUE THREAD

**Issue by janithcmw** [wso2/analytics-apim#1413]
In the loading the widgets in APIM-Analytics dashboard-3.1.0, the "Widget.js" level timeout was exceeded. Please refer to the below image.

![image-2020-07-13-14-33-58-777](https://user-images.githubusercontent.com/47592448/88888123-5a79a580-d25b-11ea-9b33-239539392ae6.png)

**Affected Product Version:**
3.1.0

**Comment by TanyaM** [comment]
Fixed with https://github.com/wso2/carbon-dashboards/commit/f8ec4a3d6f842154420c01914886d42334e106fc

**Comment by TanyaM** [comment]
This issue needs to be fixed at the base widget level at https://github.com/wso2/carbon-dashboards/blob/master/base-widget/src/Widget.jsx#L189
