### ISSUE TITLE
dashboard.bat starts with error

### ISSUE THREAD

**Issue by rajputvishwas** [wso2/analytics-apim#1445]
**Description:**

I tried quick setup steps for APIM-Analytics given at https://apim.docs.wso2.com/en/latest/learn/analytics/configuring-apim-analytics/ my worker.bat and wso2server.bat starts normally. But dashboard.bat throws some errors while starting.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
wso2 analytics 3.1
**OS, DB, other environment details and versions:**    
windows 10 x 64
**Steps to reproduce:**

https://apim.docs.wso2.com/en/latest/learn/analytics/configuring-apim-analytics/

**Related Issues:**

[worker080820.txt](https://github.com/wso2/analytics-apim/files/5045095/worker080820.txt)
[apim080820.txt](https://github.com/wso2/analytics-apim/files/5045096/apim080820.txt)
[analytics080820.txt](https://github.com/wso2/analytics-apim/files/5045097/analytics080820.txt)

**Comment by RAVEENSR** [comment]
Hi @rajputvishwas,

Could you please tell us what is the exact Java 8/11 version you are using?

Ex: 
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.212-b04, mixed mode)

**Comment by rajputvishwas** [comment]
Hi @RAVEENSR 

PFB Java version details.

openjdk version "1.8.0_202"
OpenJDK Runtime Environment (build 1.8.0_202-b08)
Eclipse OpenJ9 VM (build openj9-0.12.1, JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20190205_265 (JIT enabled, AOT enabled)
OpenJ9   - 90dd8cb40
OMR      - d2f4534b
JCL      - d002501a90 based on jdk8u202-b08)

**Comment by RAVEENSR** [comment]
Hi @rajputvishwas 

We do not support OpenJDK with Eclipse OpenJ9. Please refer [1] for compatible JDKs. Please try with a supported JDK.

[1] https://apim.docs.wso2.com/en/latest/InstallAndSetup/ProductCompatibility/#tested-operating-systems-and-jdks
