### ISSUE TITLE
Improvement for Siddhi Aggregation process

### ISSUE THREAD

**Issue by prasa7** [wso2/analytics-apim#1474]
**Description:**

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by RAVEENSR** [comment]
Fixed with the following PRs: 
https://github.com/wso2-support/siddhi/pull/89
https://github.com/wso2-support/siddhi/pull/90
https://github.com/wso2-support/siddhi/pull/91
https://github.com/wso2-support/siddhi/pull/92
