### ISSUE TITLE
Throwing NPE exception when during the month report through Analytics 3.2.0

### ISSUE THREAD

**Issue by rizmir22** [wso2/analytics-apim#1504]
**Description:**
When we create the monthly report to see the stats in the analytics, a single page can have a maximum 25 raws/records.
If it has more than 25 rows/ records it will include it on the next page. The problem is, when there are exactly 25 raws, it will throw an NPE and it seems there is an issue with the pagination

**Suggested Labels:**
APIM Analytics-3.2.0, Bug

**Suggested Assignees:**

**Affected Product Version:**
APIM Analytics-3.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Create a report with exactly 25 records for the specific month

**Related Issues:**

**Comment by npamudika** [comment]
Fixed with https://github.com/wso2/analytics-apim/pull/1508
