### ISSUE TITLE
[APIM-Analytics-3.2.0] Purging task halted Error on Analytics Node

### ISSUE THREAD

**Issue by Hashini-Deshappriya** [wso2/analytics-apim#1530]
**Description:**
When there is an aggregation issue, what we are usually doing is restarting the worker node and simulate events to initiate the aggregation. But even if we ask to do that, for throttling and fault aggregation flows, an event might not trigger.
So the ApiThrottledOutAgg and the Falult aggregations will remain in the previous state and the rest of the aggregations will trigger and the issues of other aggregations will resolve. But after some time when the automatic purging is triggered (default after 60 min) the "Purging task halted!!!" error will continuously printed for throttling and fault flows and the purging will also halt.

**[2022-05-16 05:12:17,843] ERROR {io.siddhi.core.aggregation.IncrementalDataPurger} - Purging task halted!!!. Data purging for table: ApiThrottledOutAgg_HOURS with a retention of timestamp : 1644556337810 didn't executed since parent ApiThrottledOutAgg_DAYS table does not contain values of above period.** 

Hence we need to fix this at code level.

**Affected Product Version:**
APIM - Analytics -3.2.0

**Comment by HeshanSudarshana** [comment]
Public fix added with https://github.com/wso2/carbon-analytics/pull/2002
