### ISSUE TITLE
Need to enforce the TLS 1.2 version for the SMTP. 

### ISSUE THREAD

**Issue by Gayanthakaushal** [wso2/analytics-apim#1546]
**Description:**
Currently, the apim-analytics-2.6.0 version is using javax.mail version 1.5.6. But TLS 1.2 is available javax.mail version 1.6 onwards[1]. Therefore can we use the javax.mail version 1.6 for the SMTP mail sending.

**Affected Product Version:** apim-analytics-2.6.0

[1] - https://sites.google.com/site/pawneecity/amazon-aws/aws-ses#h.dq6v2r7tq0gy

**Comment by YasasRangika** [comment]
Closing this issue as this does not apply to the master branch.
