### ISSUE TITLE
Alert suppression for some alerts is done via a history table. Need to move this to a time window

### ISSUE THREAD

**Issue by fazlan-nazeem** [wso2/analytics-apim#415]
**Description:**
 Some of the alerts are suppressed via a history table. Some have been done via a time window. Time window solution seems to be a better choice. 

In future, we need to try to move the history table implementations to a time window.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
2.1.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ruks** [comment]
@fazlan-nazeem Is this fixed now or is this use case is still valid?

**Comment by fazlan-nazeem** [comment]
Looks like we have implemented time window based suppression for all alerts. Hence closing.
