### ISSUE TITLE
Generated gadets does not work with real time source

### ISSUE THREAD

**Issue by dnwick** [wso2/analytics-apim#421]
**Description:**
Gadget is created with gadget wizard using Real time data source , does not work after sending real time data.

**Affected Product Version:**
APIM analytics 2.1.0

**Steps to reproduce:**
- Create a gadget using gadget generation wizard using Realtime data source and drag drop it to a dashboard.
- send events to specific stream

**Comment by fazlan-nazeem** [comment]
gadget generatio is not supported in apim analytics via the wizard
