### ISSUE TITLE
[Alert][2.0.0] requestPerApiCountStream and responsePerApiCountStream gets aggregated counts

### ISSUE THREAD

**Issue by rmsamitha** [wso2/analytics-apim#422]
**Description:**
HealthAvailability alerts is not working properly because of this issue. What happens here is in 'APIMAnalytics-HealthAvailabilityPerMinAlert-HealthAvailabilityPerMin-realtime1' execution plan, below queries are wrong.

/* timeBatch used because Minutely updates are needed */
@info(name = 'query1')
from requestPerMinStream
select  api_version, apiPublisher, tenantDomain, sum(total_request_count) as  requestsPerMinPerApi
group by api_version, tenantDomain
insert into requestPerApiCountStream;

@info(name = 'query2')
from responseSummaryStream
select  api_version, tenantDomain,  sum(total_response_count) as  responsesPerMinPerApi
group by api_version, tenantDomain
insert into responsePerApiCountStream;

If consider the 1st query, requestsPerMinPerApi value gets aggregated after each minute. That is wrong.

**Suggested Labels:**
Alerts, HealthAvailability

**Affected Product Version:**
2.0.0

**Fix suggesting:**

Removing getting the sum as below

/* timeBatch used because Minutely updates are needed */
@info(name = 'query1')
from requestPerMinStream
select  api_version, apiPublisher, tenantDomain, total_request_count as  requestsPerMinPerApi
group by api_version, tenantDomain
insert into requestPerApiCountStream;

@info(name = 'query2')
from responseSummaryStream
select  api_version, tenantDomain, total_response_count as  responsesPerMinPerApi
group by api_version, tenantDomain
insert into responsePerApiCountStream;

**Comment by fazlan-nazeem** [comment]
closing this since it is solved.
