### ISSUE TITLE
UX Scenario to consider

### ISSUE THREAD

**Issue by shavantha** [wso2/analytics-apim#474]
**Description:**
When a user accesses the analytics  some may want to by default view "My APIs" first rather than "All APIs" but some may want the current view. Can we have a way for the users to configure this for their products so that they dont want to allways click on "MyAPIs" for each analytics graph.

This way we can improve the User experience and cater based on the customer needs.

**Comment by ruks** [comment]
This is improved in 3.2.0 onwards by restricting dashboards to business analytics and API analytics. It provide a separate view for API owners and Others. 
Hence closing.
