### ISSUE TITLE
No identity-anonymization-tool configuration in APIM analytics.

### ISSUE THREAD

**Issue by chalitha87** [wso2/analytics-apim#477]
**Description:**
In order to test gdpr related scenarios, we couldn't find any Identity-anonymization-tool configuration in APIM analytics pack

**Suggested Labels:**
Type/Bug
Severity/Blocker
Priority/Highest
Affected/APIM-analytics update 9

**Affected Product Version:**
APIM-analytics 2.1.0 update 9

**OS, DB, other environment details and versions:**    
APIM-analytics 2.1.0 update 9 fresh pack

**Comment by tharikaGitHub** [comment]
Available in newer releases of APIM-Analytics.
