### ISSUE TITLE
Outdated links in the APIM Analytics 2.1.0 Management Console

### ISSUE THREAD

**Issue by Mariangela** [wso2/analytics-apim#501]
**Description:**
There are four outdated links in the APIM Analytics Management Console (https://<IP>:9444/carbon) sign in page, as mentioned below.

1. User Guide - Change this link to https://docs.wso2.com/display/AM210/Analytics
2. Issue Tracker - Link this to https://github.com/wso2/analytics-apim/issues/
3. Docs - Change this link to https://docs.wso2.com/display/AM210/Analytics
4. About - Remove this link. (I already had a discussion with NuwanD in this regard and he confirmed my suggestion).

**Suggested Assignees:**
Chanaka Jayasena

**Affected Product Version:**
APIM Analytics 2.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Start API-M 2.1.0
Access https://<IP>:9444/carbon

**Related Issues:**
N/A

**Comment by fazlan-nazeem** [comment]
Not relevant for current versions.
