### ISSUE TITLE
Wrong year in license version

### ISSUE THREAD

**Issue by vlna** [wso2/analytics-apim#527]
**Description:**
Second line of file `LICENSE` should be reverted back to `Version 2.0, January 2004`. It looks like typo or unintended change.

**Suggested Labels:**
Priority/Low, Typo

**Affected Versions:**
eeab96f25a4e6f6ff26f907f52fc282607e04bba-latest (24188b4f603775932320f10d15507bb26687e74c)

**Comment by fazlan-nazeem** [comment]
@vlna  Thank you for reporting this.

**Comment by pahans** [comment]
2016 is the correct year.

**Comment by vlna** [comment]
Hi @pahans, year 2016 in `LICENSE` is wrong. The year is related to release of license itself and not related to your code.

**Comment by pahans** [comment]
@vlna Yes, you are correct.  Reopened the issue.
