### ISSUE TITLE
Analytics affects when there are empty fields in JWT.

### ISSUE THREAD

**Issue by nalakas** [wso2/analytics-apim#564]
**Description:**
there are some cases null in JWT in following values when we send those data into analytics.
*apiPublisher
*username
*applicationId
*applicationName
*subscriber
*subscriberTenantDomain

from those values, one or more values can be null. when values from those fields are null analytics is not working.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
2.5.0
**OS, DB, other environment details and versions:**    
mac os high sierra , h2 database

**Steps to reproduce:**
call using JWT which has one or more empty fields in JWT using micro-gateway.
(JWT which is not subscribed to any API[empty apiPublisher])

set the fields values empty in subscription filter

**Related Issues:**

**Comment by fazlan-nazeem** [comment]
We have handled null values before sending the events to analytics. Therefore there cannot be any null events published to analytics.
