### ISSUE TITLE
Product version is stated as 2.1.1.SNAPSHOT in carbon.xml file of APIM Analytics-2.5.0 

### ISSUE THREAD

**Issue by iloshinik** [wso2/analytics-apim#580]
**Description:**
The product version in the carbon.xml file of the wso2am-analytics-2.5.0, is stated as 2.1.1.SNAPSHOT.

**Suggested Labels:**
apim-analytics

**Affected Product Version:**
2.5.0

**Comment by fazlan-nazeem** [comment]
not relevant for current versions as there is no carbon.xml
