### ISSUE TITLE
Error "Problem accessing: /. Reason: Not Found" when I try to log in Api Manager after configure Api Analytics.

### ISSUE THREAD

**Issue by iransosa** [wso2/analytics-apim#596]
**Description:**
I've installed Wso2 Api Manager a few days ago follow this intructions:
1. I've downloaded https://wso2.com/api-management/install.
2. I've installed using the wizard in C:\Program Files\WSO2\API Manager directory.
3. I've initialize Api Manger console, then created some apis from https://localhost:9443/publisher .

Now, I want to see some statistics (https://192.168.138.117:9443/publisher/site/pages/all-statistics.jag?page=api-usage-user&stat=all-stat). I've read that API Analytics has to be configured, so I carried out the following steps (https://docs.wso2.com/display/AM260/Configuring+APIM+Analytics#ConfiguringAPIMAnalytics-Step1-DownloadandinstallWSO2API-M).

1. I download it (https://wso2.com/api-management/install/analytics).
2. Unzip file in C:\WSO2\wso2am-analytics-2.6.0.
3. I've created and Environment Variables called JAVA_HOME. In value field, I typed the installation path of the Java Development Kit, C:\Program Files\Java\jdk1.8.0_191.
4. I edited the tag <Analytics><Enabled>true</Enabled> in the file "C:\Program Files\WSO2\API Manager\2.6.0\repository\conf\api-manager.xml".
5. I exec this command in cmd windows: "C:\WSO2\wso2am-analytics-2.6.0>worker.bat -run". It excecuted some process and aparentely everything was ok.
6. Finally, I run another windows console and exec: "C:\Program Files\WSO2\API Manager\2.6.0\bin>wso2server.bat -run".

Now, when I try to log in https://localhost:9443/publisher, /store o /carbon, I'm getting this error:

> Problem accessing: /. Reason: Not Found

If I only lunch the Api Manager, it works perfectly but I can't get the statistics.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
Api Manager 2.6.0
wso2am-analytics-2.6.0

**OS, DB, other environment details and versions:**    
Windows 10

**Steps to reproduce:**

**Related Issues:**

**Comment by pahans** [comment]
I tried to reproduce this on 3.0.0 and could not reproduce.
