### ISSUE TITLE
Analytics Failover configurations gives an error

### ISSUE THREAD

**Issue by ksdperera** [wso2/analytics-apim#599]
**Description:**
 Since the APIM Analytics HA passive node thrift server is disabled, the thrift connection error log keeps printing on the APIM server. Even though we have configured as Failover configuration seems API Manager is still trying to connect to the passive node.

**Affected Product Version:**
APIM Analytics 2.6.0

**Steps to reproduce:**
 Configure the Failover configuration in APIM node

**Comment by lasanthaS** [comment]
This has been fixed by following PRs. Hence closing the issue.
- https://github.com/wso2/carbon-analytics-common/pull/578
- https://github.com/wso2/carbon-analytics-common/pull/579
