### ISSUE TITLE
APIM alerts status is shown incorrectly after re start

### ISSUE THREAD

**Issue by Rajith90** [wso2/analytics-apim#600]
**Description:**
When we disable alters from API manager admin console and then restart the analytics server. Then the alerts related execution plans are not shown in the management console of anlytics server. But from admin app, the status is again shown as active

**Affected Product Version:**
analytics 2.1.0, apim 2.1.0

**Steps to reproduce:**

- Deactivate alerts from the admin app
- Restart the analytics server
- Again alerts will be shown as active in admin app, but the execution plans are not visible in the management console of the analytics server.

**Related Issues:**
https://github.com/wso2/product-das/issues/280

**Comment by fazlan-nazeem** [comment]
This view has been removed from admin console. Alert params have to be changed via the business-rules app from 3.0 release.
