### ISSUE TITLE
[APIM-Analytics][2.6.0] Performance hit when analytics is enabled

### ISSUE THREAD

**Issue by dinusha92** [wso2/analytics-apim#602]
**Description:**

It was observed when APIM alerts is enabled for the 2.6.0 version, there is a performance degrade. This was caused by the alerts related Siddhi application in APIM analytics 2.6.0. Hence they needs to be reviewed and modified accordingly.
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by pravindeok** [comment]
when this is coming?

**Comment by Niveathika92** [comment]
@pravindeok We have identified the bottlenecks and fixed them and currently doing perf tests on the suggested changes.

**Comment by Niveathika92** [comment]
Fixed PR https://github.com/wso2/analytics-solutions/pull/271

**Comment by ruks** [comment]
Closing the issue since this is fixed with the above PRs.
