### ISSUE TITLE
Add a Health check Rest API for API Manager Analytics which is based on SP

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/analytics-apim#606]
**Description:**
We should add a Health Check Rest API for API Manager Analytics which is base on Stream Processor.

**Affected Product Version:**
APIM Analytics 2.6.0

**Comment by fazlan-nazeem** [comment]
This is now supported in the worker profile. The sample curl command is as follows

`curl -k -X GET http://localhost:9091/health`

**Comment by fazlan-nazeem** [comment]
We will be adding a health check for the dashboard profile as well.
