### ISSUE TITLE
Add recent APIM analytics stabilizing fixes to the SP based releases

### ISSUE THREAD

**Issue by minudika** [wso2/analytics-apim#611]
**Description:**
Following fixes should be added to SP based APIM analytics releases

1. https://github.com/siddhi-io/siddhi/pull/1293
2. https://github.com/siddhi-io/siddhi/pull/1306
3. https://github.com/siddhi-io/siddhi/pull/1308
4. https://github.com/siddhi-io/siddhi/pull/1311
5. https://github.com/siddhi-io/siddhi-store-rdbms/pull/166
6. https://github.com/wso2/analytics-solutions/pull/297
7. https://github.com/wso2/analytics-solutions/pull/298
9. https://github.com/wso2/product-sp/issues/1013

**Comment by ruks** [comment]
> siddhi-io/siddhi#1293
> siddhi-io/siddhi#1306
> siddhi-io/siddhi#1308
> siddhi-io/siddhi#1311
> siddhi-io/siddhi-store-rdbms#166
SIddhi and Store RDBMS is already upgraded in Analytics 3.2.0

> wso2/analytics-solutions#297
> wso2/analytics-solutions#298
These fixes are already there in APIM analytics beta.

Hence closing.
