### ISSUE TITLE
Using configuration option with API-M alerts for AbnormalResponseAndBackendTimeDetection disables the execution plan

### ISSUE THREAD

**Issue by tgtshanika** [wso2/analytics-apim#612]
> **Description:**
> When we try to configure some of the values for the AbnormalResponseAndBackendTimeDetection alert configuration using the admin app, the relevant execution plan gets disabled once the configuration are saved. This is due to one of the required element for the stream definition gets removed when the plan gets redeployed after the config change.
> 
> In this case the affected stream is responseSummaryStream and the missing value was " _timestamp long" from the stream definition.
> 
> The backend error when plan is validated is as below.
> 
> ```
> Exception when validating execution plan
> org.wso2.carbon.event.processor.core.exception.ExecutionPlanDependencyValidationException: No of attributes in stream org.wso2.apimgt.statistics.perMinuteResponse:1.0.0 do not match the no of attributes in Siddhi stream
> ```

By @Kishanthan from https://wso2.org/jira/browse/ANLYAPIM-163

**Comment by fazlan-nazeem** [comment]
Editing alert params via admin portal is not supported anymore.
