### ISSUE TITLE
Improve APIM analytics related queries to reduce DB errors.

### ISSUE THREAD

**Issue by tgtshanika** [wso2/analytics-apim#613]
> **Description:**
> Improve the rdbms-config.xml queries to reduce DB level exceptions.
> 
> Fix the DROP INDEX QUERY in PostgreSQL section.
> ```
>         <recordTableDeleteQueries>
>             <query>DROP INDEX {{TABLE_NAME}}_PARTITION_KEY ON {{TABLE_NAME}}
>              </query>
>             <query>DROP INDEX {{TABLE_NAME}}_TIMESTAMP ON {{TABLE_NAME}}</query>
>             <query>DROP TABLE IF EXISTS {{TABLE_NAME}}</query>
>         </recordTableDeleteQueries>
> ```
> Improve the CREATE INDEX query in PostgreSQL section.
> ```
>        <recordTableInitQueries>
>             <query>CREATE TABLE {{TABLE_NAME}} (record_id VARCHAR(128), timestamp BIGINT, data BYTEA, partition_key
>                 INTEGER, PRIMARY KEY(record_id))</query>
>             <query>CREATE INDEX {{TABLE_NAME}}_TIMESTAMP ON {{TABLE_NAME}} (timestamp)</query>
>             <query>CREATE INDEX {{TABLE_NAME}}_PARTITION_KEY ON {{TABLE_NAME}} (partition_key)</query>
>         </recordTableInitQueries>
> ```

By @gnudeep from https://wso2.org/jira/browse/ANLYAPIM-159

**Comment by ruks** [comment]
Since analytics are refactored, DAS based analytics not using. SP based analytics didn't report this kind of issue and hence closing.
