### ISSUE TITLE
Oracle DB it's not supported

### ISSUE THREAD

**Issue by tgtshanika** [wso2/analytics-apim#614]
> **Description**
> When configuring API-M 2.1.0 with Oracle database 11.2.0.1 ( driver ojdbc6.jar) after the first start cannot start propertly with the following error:
> ```
> TID: [-1234] [] [2018-01-09 00:17:17,710] ERROR
> {org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceComponent} - Error in activating analytics data service: null {org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceComponent}
> java.lang.RuntimeException
> at org.wso2.carbon.analytics.datasource.rdbms.RDBMSAnalyticsRecordStore$RDBMSResultSetIterator.next(RDBMSAnalyticsRecordStore.java:881)
> at org.wso2.carbon.analytics.datasource.rdbms.RDBMSAnalyticsRecordStore$RDBMSResultSetIterator.hasNext(RDBMSAnalyticsRecordStore.java:843)
> at org.apache.commons.collections.IteratorUtils.toList(IteratorUtils.java:848)
> at org.apache.commons.collections.IteratorUtils.toList(IteratorUtils.java:825)
> ```
> 
> That error its related with the Datasource WSO2_ANALYTICS_EVENT_STORE_DB and table ANX_8GEKYOMM_ , which has the values
> -1000	1530118471919	null	68
> -1234	1530118476841	null 87
> When API-M Analytics stop and start again, the code in the class "org.wso2.carbon.analytics.datasource.rdbms.RDBMSAnalyticsRecordStore" located in "org.wso2.carbon.analytics.datasource.rdbms_1.3.0.jar" get the nulls and throws an error that prevent teh product form starting.
> As a work around deleting the values of the table ANX_8GEKYOMM_ permits the start up of Analytics....but then the error it happens again when starting the next time.
> 
> If the Datoasurce is configured with H2, there is no problem in this case....so it's pretty clear that there is a big issue with Oracle DB use in this API-M Analytics 2.1.0 relesease.
> This has caused us a lot of trouble since the client just uses Oracle DB.
> Thanks in advance
> 
By JAVIER SOTO from https://wso2.org/jira/browse/ANLYAPIM-180

**Comment by fazlan-nazeem** [comment]
We have eliminated indexing and spark. Works fine in oracle in latest releases.
