### ISSUE TITLE
Include capability to add data level permission in analytics.

### ISSUE THREAD

**Issue by tgtshanika** [wso2/analytics-apim#615]
> **Description:**
> Currently, when accessing the data through data explorer in the management console, we only consider UI and service level permissions. And also through rest endpoints, we can provide permissions operation wise, but not in data level. Better to include data level permission as well (i.e. event table wise).

By @IndunilRathnayake from https://wso2.org/jira/browse/ANLYAPIM-168

**Comment by ruks** [comment]
data explorer is DAS based feature and since analytics is refactored with SP analytics. This feature is not available now. Hence closing.
