### ISSUE TITLE
Include capability to add gadgets level permissions in analytics and das

### ISSUE THREAD

**Issue by tgtshanika** [wso2/analytics-apim#616]
**Description:**
Currently, it's only supported to have dashboard level permissions, but it'll be better to include gadgets level permissions as well in analytics and das.

By @IndunilRathnayake from https://wso2.org/jira/browse/ANLYAPIM-167

**Comment by ruks** [comment]
Dashboard level permissions are supported in APIM analytics 3.0.0 onwards. And DAS based analytics and Dashboards are not relevant here. 
Hence closing.
