### ISSUE TITLE
[APIM Analytics 2.1.0] Need to prevent data insertion to DAL tables in default analytics CAPP to improve performance

### ISSUE THREAD

**Issue by tgtshanika** [wso2/analytics-apim#617]
> **Description:**
> Need to prevent data insertion to DAL tables in default analytics CAPP to improve performance. There are many unwanted inserts on the DB's slowing down the TPS. If the system uses the RDBMS client, it should only insert to JDBC and not DAL and should not index ( the analytics data, not the alert data). If the system uses the REST api (DAL), it should not insert data to JDBC.
> 
> In other words, we should bypass the DAL(whenever possible), fetch data from raw data tables and insert to summary tables.

By @chamindias from https://wso2.org/jira/browse/ANLYAPIM-158

**Comment by ruks** [comment]
Capps and DAL is not relevant to SP based analytics. Hence closing.
