### ISSUE TITLE
Cannot create index for API_REQUEST_SUMMARY

### ISSUE THREAD

**Issue by tgtshanika** [wso2/analytics-apim#618]
> **Description:**
> API Manager Analytics can't create primary keys for API_REQUEST_SUMMARY table. The message written in log to correct it says "Drop the existing clustered index PK_API_REQU_1E2444655FEE3F5E", but there aren't any PK object in database.
> 
> See logs in Attachment
> 
> Thanks and Regards
> 
> **OS, DB, other environment details and versions:**    
> Installation summary 
> Database: Microsoft SQL Server 2014
> Schemas: apimreganalyticsdb, apimstatdb, apimeventdb and apimprocesseddb
> API Manager Analytics: 2.1.0

By Wesley Forti from https://wso2.org/jira/browse/ANLYAPIM-156

**Comment by tgtshanika** [comment]
Please refer https://wso2.org/jira/browse/ANLYAPIM-156 for logs and configs related to the issue

**Comment by ruks** [comment]
API_REQUEST_SUMMARY and indexes are not relevant to new analytics architecture. Hence closing.
