### ISSUE TITLE
Summarized data insertion to WSO2AM_STAT_DB might fail due to very long primary keys

### ISSUE THREAD

**Issue by tgtshanika** [wso2/analytics-apim#619]
> **Description:**
> This can happen in any APIM analytics version (1.7.0 .. 2.10), since most of the DBs have non-configurable primary key lengths. As some of the tables contains primary keys consist of several fields (resourcepaths, apipublisher, api, tenant, version.. etc), the total primary key length can exceed the maximum primary key length allowed by the database type. We need to introduce one primarykey (may be a hash from the above mentioned fields), so we can have a small primary key to fit most of RDBMS. Also we will have to find a way to migrate from the older STAT DB to new stat db.

By @gimantha from https://wso2.org/jira/browse/ANLYAPIM-152

**Comment by ruks** [comment]
Not relevant to the latest analytics and didn't reproduce such an issue in new aggregated tables. Hence closing.
