### ISSUE TITLE
Summarization of stats fails if the user-agent header is missing from the request

### ISSUE THREAD

**Issue by tgtshanika** [wso2/analytics-apim#620]
> **Description:**
> In APIM analytics, we extract the os and the client from the user-agent header of the request. This os field is a primary key of the browser_summary table in WSO2AM_STAT_DB. If someone by mistake did not assign the user-agent header, we will have raw data without the user-agent header and this will cause the spark scripts to fail as os is going to be null and we cannot insert null values to primary keys. So,
> 
> 1. We have to modify the spark scripts to check if the user-agent header is null in the raw request statistics table and if it is null then we have to set some default value (may be "NOT_FOUNG")
> or 
> 2. We have to change the sprak UDF from which the os and client is extracted to set a default value.
> 
> There are some occasions where the users might invoke the apis without setting the user-agent (e.g. tools like jmeter)

By @gimantha from https://wso2.org/jira/browse/ANLYAPIM-151

**Comment by ruks** [comment]
This is already fixed in the latest analytics version and hence closing.
