### ISSUE TITLE
Analytics Apim Artifact names need to be corrected according to the common naming convention.

### ISSUE THREAD

**Issue by tgtshanika** [wso2/analytics-apim#621]
> **Description:**
> Please follow the "Standards and Guidelines for Analytics Artifacts" documentation and rename the artifact name accordingly.

By Sajith Dimal from https://wso2.org/jira/browse/ANLYAPIM-145

**Comment by ruks** [comment]
These artifacts are not relevant to new SP based analytics. Stream names and attributes are already in the correct format. Hence closing.
