### ISSUE TITLE
Provide a Time Picker to filter alerts based on a time period

### ISSUE THREAD

**Issue by tgtshanika** [wso2/analytics-apim#622]
> **Description:**
> Currently, alert dashboard doesn't have the capability to filter alert based on the given time period. For an example, if the admin wants to check the generated alerts within last 7 days or within few weeks, he/she may not be able to do it right now. So for this purpose, a time picker would be better to integrate with alert dashboard.
> 
> **Environment**
> API Manager 2.0.0 RC4, API Manager Analytics 2.0.0 RC3, MSSQL 2012 Database, Java 1.8.0_72, Firefox 45.0, Google Chrome 49.0.2623.87 (64-bit)
> 
By @maneeshaheshan from https://wso2.org/jira/browse/ANLYAPIM-120

**Comment by ruks** [comment]
This is fixed in APIM 3.2.0 beta, in the monitoring dashboard.
![image](https://user-images.githubusercontent.com/1345278/87131456-11fd4680-c2b2-11ea-8915-1ba1ca6f67d4.png)

Hence closing.
