### ISSUE TITLE
No email generation for 'Health Availability' alert

### ISSUE THREAD

**Issue by tgtshanika** [wso2/analytics-apim#623]
> **Description:**
> Pre-Conditions -
> 
> - 'output-event-adapters.xm'l should be configured with a desired email configs in each analytics node
> - Add a receipent email in 'manage alert types' by ticking Health Availability in either publisher or admin portal
> - Few 'Health Availability' alerts should be generated
> 1. Go to 'Alert Dashboard' in Admin Portal
> 
> Health availability alerts should be available (check attachment) . But no email revived by recipient email configured for 'Health Availability'
> 
> Note - Several alerts like 'Unseen Source IP Access', 'Abnormal Request Count' and 'Abnormal Resource Access' have generated email notifications. Please check with other alert types too.
> 
> **OS, DB, other environment details and versions:**    
> API Manager RC4 Standalone Pack
> APIM Analytics RC3 Minimum HA cluster with 2 nodes
> All nodes (including standalone pack) pointed to MSSQL 2012
> Browsers - Firefox 45.0 and Google Chrome 49.0.2623.87 (64-bit)
> Java 1.8.0_72
> 
> ![Health Availability in alert dashaboard](https://user-images.githubusercontent.com/4471756/58478341-74a98680-8173-11e9-95f6-09b5937b1b45.png)
>

**Comment by fazlan-nazeem** [comment]
Works fine in master branch.
