### ISSUE TITLE
[APIM Analytics 2.0.0] HealthAvailabilityPerMin Siddhi App Improving

### ISSUE THREAD

**Issue by tgtshanika** [wso2/analytics-apim#625]
> **Description:**
> Because of the existing HealthAvailabilityPerMin, it could cause analytics stops receiving event causing APIM to cause ReadTimeOuts.
> APIMAnalytics-HealthAvailabilityPerMinAlert-HealthAvailabilityPerMin-realtime1 execution plan which caused extraordinarily high DB and indexing inserts which caused the other inserts to be extremely slow thus causing the stat updates to be slow.

By @dinusha92 from https://wso2.org/jira/browse/ANLYAPIM-176

**Comment by fazlan-nazeem** [comment]
This siddhi app is redesigned with performance improvements.
