### ISSUE TITLE
Wrong Column Name in API_LAST_ACCESS_TIME_SUMMARY summary table

### ISSUE THREAD

**Issue by tgtshanika** [wso2/analytics-apim#627]
> **Description:**
> API_LAST_ACCESS_TIME_SUMMARY table is showing last access time of an API.
> This table contains a column column name which is MAX_REQUEST_TIME. This MAX_REQUEST_TIME indicates the last access time. Since this is confusing this should be changed into LAST_ACCESS_TIME.
> 
> The root cause for this could be propagated from execution plan APIMAnalytics-LastAccessTime. Here requestTime is takes as max_request_time.
> 
> ```
> @from(eventtable = 'analytics.table' , table.name = 'API_LAST_ACCESS_TIME_SUMMARY',  primary.keys = 'tenantDomain,apiPublisher,api', wait.for.indexing = 'false')
> define table lastAccessTable (tenantDomain string, apiPublisher string, api string, version string, userId string, context string, max_request_time long);
> 
> @info(name = 'query_lastAccess')
> from requestPerMinStream#window.timeBatch(1 min)
> select tenantDomain, apiPublisher, api, version, userId, context, requestTime as max_request_time
> insert into lastAccessTable;
> ```
> Hence it is needed to refactor max_request_time as last_access_time in both execution plan and DB scripts.
By @dinusha92 from https://wso2.org/jira/browse/ANLYAPIM-169

**Comment by ruks** [comment]
This is already fixed in newer versions[1]. Hence closing.

[1] https://github.com/wso2/analytics-apim/blob/v3.1.0/features/org.wso2.analytics.apim.feature/src/main/resources/siddhi-files/APIM_ACCESS_SUMMARY.siddhi#L104
