### ISSUE TITLE
Remove unwanted indices and add wait.for.indexing for APIMAnalytics-HealthAvailabilityPerMinAlert-HealthAvailabilityPerMin-realtime1.siddhiql

### ISSUE THREAD

**Issue by tgtshanika** [wso2/analytics-apim#628]
> **Description:**
> There are couple of changes we need to do to improve the execution plan: APIMAnalytics-HealthAvailabilityPerMinAlert-HealthAvailabilityPerMin-realtime1.siddhiql
> 
> 1. Add wait.for.indexing
> 2. Removing unwanted indices
By @malinthaprasan from https://wso2.org/jira/browse/ANLYAPIM-162

**Comment by ruks** [comment]
Since analytics is refactored from APIM 2.6.0 onwards WSO2 DAS related features and functions no longer used. Hence closing.
