### ISSUE TITLE
Better to have integer values for Application Errors count in Log Analyzer

### ISSUE THREAD

**Issue by tgtshanika** [wso2/analytics-apim#630]
> **Description:**
> Pre-Condition - Few application errors have to be made (ex - invoke with an invalid access token)
> 
> 1. Go to Admin Dashboard.
> 2. Go to Log Analyzer -> Application Errors
> 
> Application error count in 'Errors Distribution' bar chart showed with decimal values (Check attachment1). Since a count can't be a decimal, it's better to have the count in integer values.
> 
> **OS, DB, other environment details and versions:**    
> APIM 2.0.0-SNAPSHOT Nightly build - 06/06/2016, API-M Analytics 1.0.0-SNAPSHOT Jenkins build - 141, Standalone, H2 Database, Java 1.8.0_72, Firefox 45.0, Google Chrome 49.0.2623.87 (64-bit)
By @maneeshaheshan from https://wso2.org/jira/browse/ANLYAPIM-52

**Comment by fazlan-nazeem** [comment]
log analyzer is not supported anymore. Hence closing.
