### ISSUE TITLE
Better if the content of an Email notification for a subscribed alert is more visible

### ISSUE THREAD

**Issue by tgtshanika** [wso2/analytics-apim#631]
> **Description:**
> Pre-Conditions -
> 
> Email configurations should be setup in output-event-adapters.xml
> An API (ex-api1) should be available with at least one resource.
> A user should be available (ex-user1) and should set an email for all the types of alerts in 'Manage Alert Types' in Store
> 1. Invoke any available resource of api1 (more than 1000 times).
> 2. Go to assigned email address to receive alerts
> 
> An email should be received (check attachment)
> 
> Email body is not much clear to understand at first and it's better it can divide into sections by lines (message, user, owner in each separate lines) .
> 
> Although It's good to have convenient names instead of 'method' type names such as 'alertTimestamp'

By @maneeshaheshan from https://wso2.org/jira/browse/ANLYAPIM-81

**Comment by ruks** [comment]
closing since duplicate https://github.com/wso2/analytics-apim/issues/635
