### ISSUE TITLE
Date Picker doesn't restrict only to select a date from the perticular month

### ISSUE THREAD

**Issue by tgtshanika** [wso2/analytics-apim#632]
> **Description:**
> 1. Go to Applications Time in Statistics by logged into Publisher.
> 2. Select the icon to for date picker.
> 3. Change the starting month to next month by using arrow mark in date picker ( ex- if April is the starting month of the date picker, navigate to May)
> 
> The date picker still choose a date from previous month and this should be disabled (From-To range selection at the right side also shows the date as previous month).
> 
> (Please refer attachments)
> 
> Note - This is repeating in all the statistics in Publisher except API Subscriptions.
> 
> [1] Applications time,
> 
> ![Default Picker Before Change Starting Month](https://user-images.githubusercontent.com/4471756/58494147-13dd7680-8192-11e9-8090-fb9e87ddb473.png)
> ![Time Picker after changing Starting Month](https://user-images.githubusercontent.com/4471756/58494152-150ea380-8192-11e9-8ac9-82e36fde9d4c.png)
> 
By @maneeshaheshan from https://wso2.org/jira/browse/ANLYAPIM-29

**Comment by ruks** [comment]
As analytics dashboards are refactored from 300 onwards this not relevant now. Hence closing.
