### ISSUE TITLE
Make APIM Alert Email More User Friendly

### ISSUE THREAD

**Issue by tgtshanika** [wso2/analytics-apim#635]
> **Description:**
> Currently the email that getting when triggered a APIM alert it not much user friendly. Better to use more meaningful subject with html email body. I believe we can use siddhi email template support for this.

By @harsha89 from https://wso2.org/jira/browse/ANLYAPIM-130

**Comment by ruks** [comment]
this can be done by chaning "EmailNotificationStream" in APIM_ALERT_EMAIL_NOTIFICATION.siddhi app. Hence closing.
