### ISSUE TITLE
Wrong user count in "Top users" dashboard in store

### ISSUE THREAD

**Issue by tgtshanika** [wso2/analytics-apim#636]
> **Description:**
> The first graph in "Top users" dashboard says there are 7 users for albumApps application but in the detail the view there is only six users.Actually, the Application has only 6 distinct users.
> 
> See the screenshot
> ![top-users](https://user-images.githubusercontent.com/4471756/58494620-24422100-8193-11e9-8938-d274f1122aee.png)
> 
By @ajanthan from https://wso2.org/jira/browse/ANLYAPIM-149

**Comment by fazlan-nazeem** [comment]
we have completely redesigned the charts related to these. Hence closing.
