### ISSUE TITLE
Editor permission for dashboards are not working

### ISSUE THREAD

**Issue by ruwiniwj** [wso2/analytics-apim#662]
**Description:**
When a dashboard is created and the Editor permission of the dashboard is set to 'apim_analytics:subscriber_editor', the subscribers can not edit the dashboard, they can only view it. The subscribers can edit the dashboard only when the Owner permission is set to 'apim_analytics:subscriber_owner'.

**Comment by RAVEENSR** [comment]
Fixed in https://github.com/wso2/carbon-dashboards/pull/1188
