### ISSUE TITLE
Filter options missing in the Devices Section

### ISSUE THREAD

**Issue by sanjulamadurapperuma** [wso2/analytics-apim#666]
**Description:**

When selecting a filter (for example, API Name) of an API that has not been invoked before will show the "no data available" message, but will also hide the filter options along with the graph.

![image](https://user-images.githubusercontent.com/32578617/65745236-aa0db300-e118-11e9-908f-e4de155abb74.png)

![image](https://user-images.githubusercontent.com/32578617/65745259-bdb91980-e118-11e9-8b53-5fa7d08c7d54.png)

Please note this happens to both the User Agents and Top Platforms widgets.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
3.0.0 Alpha

**OS, DB, other environment details and versions:**    
Ubuntu 18.04.2 LTS

**Related Issues:**

**Comment by ruwiniwj** [comment]
This has been fixed for all widgets with the APIM 3.0.0 release.
