### ISSUE TITLE
Append api creator to api name column in Publisher Analytics

### ISSUE THREAD

**Issue by sanjulamadurapperuma** [wso2/analytics-apim#667]
**Description:**
Store Analytics has the ability to search for an api name based on the api creator as shown below:
![image](https://user-images.githubusercontent.com/32578617/65748099-bf86db00-e120-11e9-99b4-04e738e234f6.png)

This ability is not present in Publisher Analytics.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
3.0.0 Alpha

**OS, DB, other environment details and versions:**    
Ubuntu 18.04.2LTS

**Related Issues:**

**Comment by ruwiniwj** [comment]
This has been fixed with the APIM analytics 3.0.0 release
