### ISSUE TITLE
Error when starting the server on windows

### ISSUE THREAD

**Issue by 1akshitha** [wso2/analytics-apim#701]
Following error will occur while starting the server on windows with worker.bat and stop.

"C:\APIM_T~1\WSO2AM~3.0-S\WSO2AM~1.0-S\bin\..\bin\version.txt"                                                                                                                                       Environment variable JAVA_VER_BASED_OPTS not defined                                                                                                                                                 The filename, directory name, or volume label syntax is incorrect.                                                                                                                                   JAVA_HOME environment variable is set to C:\Program Files\Java\jdk1.8.0_221                                                                                                                          CARBON_HOME environment variable is set to C:\APIM_T~1\WSO2AM~3.0-S\WSO2AM~1.0-S\bin\..                                                                                                              RUNTIME_HOME environment variable is set to C:\APIM_T~1\WSO2AM~3.0-S\WSO2AM~1.0-S\wso2\worker\bin\..                                                                                                 RUNTIME environment variable is set to worker                                                                                                                                                        Error: Could not find or load main class org.wso2.carbon.launcher.Main

**Comment by prabhatbhargav** [comment]
Hi Is anyone aware of this error: Environment variable JAVA_VER_BASED_OPTS not defined
