### ISSUE TITLE
Is there a possibility to accept analytics data over a gRPC service ?

### ISSUE THREAD

**Issue by slahirucd7** [wso2/analytics-apim#708]
**Description:**
Currently analytics data accepts over a Apache thrift service. When considering performance it's better if there is a gRPC service to pass analytics data.

This feature can enable by configuring siddhi APIM_Event_Receiver app to accept gRPC steams using Siddhi IO gRPC extension.

**Suggested Labels:**

**Comment by 7slcode7** [comment]
Solution to the above suggestion is proposed in the below link.

[https://github.com/wso2/analytics-apim/pull/702/files](url)
