### ISSUE TITLE
Request time does not get populated in API Proxy Performance table

### ISSUE THREAD

**Issue by kavishkafernando** [wso2/analytics-apim#726]
**Description:**

- Request time is not displayed in API Proxy Performance table.
- Displayed date is incorrect.

**Affected Product Version:**
wso2am-analytics-3.0.0

**OS, DB, other environment details and versions:**    
Chrome

<img width="1593" alt="Screen Shot 2019-10-23 at 11 43 10 AM" src="https://user-images.githubusercontent.com/19324135/67363420-eb17ac80-f58a-11e9-94d2-ece8cf2228ab.png">

**Comment by ruwiniwj** [comment]
This is due to there being only a single latency time data entry for the selected time range. If there are multiple latency time data entries for the selected time range, then the line graphs will be displayed properly.
