### ISSUE TITLE
[Intermittent] "ID token signature validation failed" error is thrown when logging out from Analytics Dashboards

### ISSUE THREAD

**Issue by TanyaM** [wso2/analytics-apim#729]
**Description:**
"ID token signature validation failed" is thrown from the analytics dashboard app when logging out. This was noticed when logged into both publisher and dev portal apps in the same browser. (Not in private browsers) 

<img width="1118" alt="screenshot" src="https://user-images.githubusercontent.com/3957104/67365818-fae5bf80-f58f-11e9-892c-302ae6d021c0.png">

This error is logged in the AM node at that time.

[2019-10-23 10:44:16,865] ERROR - OIDCLogoutServlet ID token signature validation failed.

**Affected Product Version:**
3.0.0-RC1

**OS, DB, other environment details and versions:**    
Chrome 72
Ubuntu 18.04

**Steps to reproduce:**
Log into publisher, devportal and analytics-dashboard apps in the same browser without using private browsing. Logout from analytics-dashboard app while logged into the other two.

This issue is intermittent.

**Comment by RAVEENSR** [comment]
Same as this issue https://github.com/wso2/analytics-apim/issues/851. This is fixed now. So can be closed.

**Comment by TanyaM** [comment]
Duplicate of https://github.com/wso2/analytics-apim/issues/851

**Comment by rahul096d** [comment]
This issue still persists in analytics 3.2.0.
