### ISSUE TITLE
"APIs Created Over Time" widget doesn't populate data when "Me" is selected from Created by drop down.

### ISSUE THREAD

**Issue by TanyaM** [wso2/analytics-apim#732]
**Description:**
Widget at Api and Application Statistics --> Apis Created Over time keeps on showing the loading gif when "Me" is selected from the Created By drop down.

**Comment by TanyaM** [comment]
When "Me" is selected from the drop down, data changes accordingly but still "All" is shown in the drop down.

**Comment by ruwiniwj** [comment]
Fixed with https://github.com/wso2/analytics-apim/pull/764
