### ISSUE TITLE
Change in the date time picker doesn't get reflected in "APIS CREATED OVER TIME" widget

### ISSUE THREAD

**Issue by TanyaM** [wso2/analytics-apim#734]
**Description:**
When a different date range is selected from the date time picker, APIS CREATED OVER TIME widget stays without changing its data. 

Widget is at Api and Application Statistics tab.

**Affected Product Version:**
3.0.0-RC1

**Comment by TanyaM** [comment]
There are some other widgets also which doesn't reflect date time changes.
Ex: Developer Statistics --> Developer Signups overtime

**Comment by ruwiniwj** [comment]
Fixed with https://github.com/wso2/analytics-apim/pull/738
