### ISSUE TITLE
Cannot see data in the multiple widgets in Tenant mode

### ISSUE THREAD

**Issue by kavishkafernando** [wso2/analytics-apim#736]
**Description:**
Cannot see data in the following widgets in Tenant mode.
**Publisher**
**Overview tab**
- OVERALL API STATS

**Usage Summary**
- OVERALL API USAGE
- TOP API USERS
- API VERSION USAGE SUMMARY
- API RESOURCE USAGE SUMMARY
- API BACKEND USAGE SUMMARY
- API LAST ACCESS SUMMARY
- API BACKEND USAGE SUMMARY

**Devices**
- TOP USER AGENTS
- TOP PLATFORMS

**API Proxy Performance**
- API LATENCY TIME

**Faults**
- TOP THROTTLED OUT APIS

**Store**
- FAULTY INVOCATIONS PER APPLICATION

**Affected Product Version:**
wso2am-analytics-3.0.0

**OS, DB, other environment details and versions:**    
Chrome

**Comment by ruwiniwj** [comment]
This is due to issue https://github.com/wso2/analytics-apim/issues/743, hence closing this issue.
