### ISSUE TITLE
"Overall Api Stats" widget is not showing any data

### ISSUE THREAD

**Issue by TanyaM** [wso2/analytics-apim#755]
**Description:**
""Overall Api Stats" widget at the "Overview" page shows "No data available" message even though there needs to be data

**Affected Product Version:**
3.0.0-RC2

**OS, DB, other environment details and versions:**    
Ubuntu 18.04
Chrome 72

**Comment by TanyaM** [comment]
This issue seems to be intermittent and started working after a restart in the dashboard profile.

**Comment by ruwiniwj** [comment]
This behaviour is not reproducible, hence closing issue.
