### ISSUE TITLE
"Top Rated Apis" widget has gone missing

### ISSUE THREAD

**Issue by TanyaM** [wso2/analytics-apim#756]
**Description:**
"Top Rated Apis" widget which was there in the "Overview" page is missing in the RC2 pack.

**Affected Product Version:**
3.0.0-RC2

**Comment by TanyaM** [comment]
This issue seems to be intermittent and started working after a restart in the dashboard profile.

**Comment by ruwiniwj** [comment]
Fixed with https://github.com/wso2/analytics-apim/pull/764
