### ISSUE TITLE
Dashboard DB cannot be used with PostgreSQL

### ISSUE THREAD

**Issue by Arshardh** [wso2/analytics-apim#759]
**Description:**
When a PostgeSQL database is setup for the dashboard DB, it gives the following error on startup:
`Caused by: java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc.PgConnection.createBlob() is not yet implemented.`

**OS, DB, other environment details and versions:**
Postgres DB version: 12.0
Postgres JDBC driver version: 42.2.8

**Comment by lasanthaS** [comment]
As per the stack trace, the issue is coming from the JDBC driver. Can you please try the same setup with an older driver version such as 9.4.x?

**Comment by Arshardh** [comment]
Tried with v9.4.1212, but the error is still reproduced
