### ISSUE TITLE
Some widgets need to be hidden for graphql APIs until we support analytics for Graphql

### ISSUE THREAD

**Issue by HiranyaKavishani** [wso2/analytics-apim#771]
**Description:**
The widgets which show the details of the resources, not working properly for Graphql APIs as the queries that used to display those  widgets have been doing a join mapping with 
AM_API_URL_MAPPING table.

**Affected Product Version:**
3.0.0 RC3

**Steps to reproduce:**
1. Invoke Graphql API
2. See the Widgets which display resource-related information

**Comment by fazlan-nazeem** [comment]
We are implementing graphQL support with the existing widgets. Hence closing this.
