### ISSUE TITLE
Overall API stats widget couples two unrelated sections

### ISSUE THREAD

**Issue by TanyaM** [wso2/analytics-apim#780]
**Description:**
Overall API stats widget has two sections for API availability and API ratings which don't have any logical relationship. The behavior is also different as API availability section needs alerts to be configured to show correct stats but Api rating section doesn't.

IMO we shoud seperate these two sections into two seperate widgets.

**Affected Product Version:**
3.0.0

**Comment by ruwiniwj** [comment]
Fixed with https://github.com/wso2/analytics-apim/pull/802
