### ISSUE TITLE
Ratings section of the overall api stats widget displays total number of stars received but not an average

### ISSUE THREAD

**Issue by TanyaM** [wso2/analytics-apim#782]
**Description:**
Ratings section of the overall api stats widget displays the total number of stars received but not an average. 

IMO it should show the average instead.

**Affected Product Version:**
3.0.0

**Steps to reproduce:**
1. Rate an api in the devportal by login in as different subscribers.
2. Refer the widget in the dashboard and you'll see a total count of stars for all subscribers.

**Comment by ruwiniwj** [comment]
Fixed with https://github.com/wso2/analytics-apim/pull/802
