### ISSUE TITLE
Legends are getting cut off in Overall Api Stats widget

### ISSUE THREAD

**Issue by TanyaM** [wso2/analytics-apim#783]
**Description:**
Please see the screenshot below.

<img width="282" alt="publisher-overview-overall-api-stats" src="https://user-images.githubusercontent.com/3957104/68266335-d8b26e00-0074-11ea-93b4-cdb1fd92061c.png">

**Affected Product Version:**
3.0.0

**OS, DB, other environment details and versions:**    
Chrome and Ubuntu

**Comment by ruwiniwj** [comment]
Closing since duplicated in https://github.com/wso2/analytics-apim/issues/739
