### ISSUE TITLE
Upgrade babel dependency in all the widgets

### ISSUE THREAD

**Issue by TanyaM** [wso2/analytics-apim#784]
**Description:**
We currently have ^6.25.0 which has browser compatibility issues and this version needs to be upgraded and all the widgets need to be thoroughly tested on different browsers.

**Affected Product Version:**
3.0.0

**Comment by pahans** [comment]
fixed with https://github.com/wso2/analytics-apim/pull/787

**Comment by pahans** [comment]
Fixed with https://github.com/wso2/analytics-apim/pull/822
