### ISSUE TITLE
Cannot create a widget

### ISSUE THREAD

**Issue by erangatl** [wso2/analytics-apim#799]
User: admin
- Go to widget generation wizard
- Enter widget name
- Click next 
This gives a blank page

![image](https://user-images.githubusercontent.com/20179540/68101618-7e8a9f00-fef4-11e9-9acd-05c4df036d5e.png)

**Comment by RAVEENSR** [comment]
This feature should be removed from the product as we do not recommend to create widgets. @TanyaM WDYT?

**Comment by TanyaM** [comment]
Yes. This will get fixed with https://github.com/wso2/analytics-apim/issues/810
