### ISSUE TITLE
Clean up package.json files of widgets

### ISSUE THREAD

**Issue by TanyaM** [wso2/analytics-apim#803]
**Description:**
Clean up package.json of widgets to remove unused npm modules and use externals whenever possible ( focus on reducing the size of bundle.js)

**Comment by pahans** [comment]
Removed some unused when refactoring for lerna. (https://github.com/wso2/analytics-apim/pull/822) and when upgrading webpack versions. To optimize further and reduce bundle size we can consider removing meterial UI/charting dependencies from widgets and move them in to dashboard.

**Comment by pahans** [comment]
I did a bundle analysis with [webpack bundle analyzer](https://chrisbateman.github.io/webpack-visualizer/) for a few widgets, biggest contributors to bundle was `react-intl`(403Kb). IMO this is acceptable ATM.
I am closing the issue for now. We might have to use chunking to optimize load time.
