### ISSUE TITLE
No Dashboards Available - Error occurred while getting the user

### ISSUE THREAD

**Issue by JUANPARBELAEZ** [wso2/analytics-apim#823]
Hello, WSO2 community.

**Description:**
I am running WSO2 API manager, in the same node along with the analytics server, and the analytics dashboard.

The analytics server is able to connect to the APIM, as seen in the **worker.sh** terminal log:

 **`[2019-11-25 05:11:36,052]  INFO {org.wso2.carbon.databridge.core.DataBridge} - user eyeqadmin connected`** 

I log into localhost:9643/analytics-dashboard.

and then get a screen like: 

![Screenshot from 2019-11-25 12-25-07](https://user-images.githubusercontent.com/15682108/69515154-3a813c00-0f80-11ea-98ac-3b736d73a36f.png)

I cannot see any way to see or set up widgets. and when I click in the button, widgets. I get this log in the terminal running **dashboard.sh**. 

 **`[2019-11-25 05:40:24,066] ERROR {org.wso2.analytics.apim.idp.client.ApimIdPClient} - Error occurred while getting the user.
`**

I inspected the jdbc:h2:/home/wso2carbon/wso2am-analytics-3.0.0/wso2/worker/database/**WSO2AM_STATS_DB**

The API calls are being registered by the analytics-server.

![Screenshot from 2019-11-25 12-52-08](https://user-images.githubusercontent.com/15682108/69515857-7b7a5000-0f82-11ea-8dc4-f3b8562bbba7.png)

 But still no graphs on the dashboard.

Hope you can guide me on how to solve this issue. 

Regards,

JP

**Suggested Labels:**
APIM 3.0.0

**Affected Product Version:**
WSO2 API Manager 3.0.0, WSO2 Analytics 3.0.0

**Comment by RAVEENSR** [comment]
@JUANPARBELAEZ  This is the same issue addressed in https://github.com/wso2/analytics-apim/issues/781. We have already fixed this issue with https://github.com/wso2/analytics-apim/pull/785.  This fix will be available in our next immediate release which is APIM Analytics 3.1.0 due in late December, 2019. In the meantime, if you need this fix you can download  3.1.0-m1 https://github.com/wso2/analytics-apim/releases/tag/v3.1.0-m1 or build the repo ad get the latest available distribution.
