### ISSUE TITLE
Blue colour back panel in widget should cover all the way to bottom

### ISSUE THREAD

**Issue by RAVEENSR** [wso2/analytics-apim#832]
**Description:**
The blue colour back panel should go all the way down and cover the widget in following widgets:

1)  APIM API Created Analytics
2) APIM Subscriptions Analytics

<img width="1673" alt="PanelError1" src="https://user-images.githubusercontent.com/19996612/69626455-b22d9480-106e-11ea-8ddc-2820e924713b.png">

<img width="1673" alt="panelError2" src="https://user-images.githubusercontent.com/19996612/69626465-b8bc0c00-106e-11ea-9f24-e7874a8279f3.png">

**Suggested Labels:**
Bug

**Suggested Assignees:**
@pahans 

**Affected Product Version:**
APIM Analytics 3.0.0

**OS, DB, other environment details and versions:**    
Mac OS Catalina

**Steps to reproduce:**
Go to publisher dashboard and check the above mentioned two widgets.

**Related Issues:**

**Comment by ruwiniwj** [comment]
A similar issue is that only some widgets have this blue color background, where as some widgets doesn't have it.

_Without background:_ 
<img width="1038" alt="without background" src="https://user-images.githubusercontent.com/20040505/70024679-d0d8e180-15c0-11ea-82f2-876065aa2eef.png">

_With background:_
<img width="549" alt="with background" src="https://user-images.githubusercontent.com/20040505/70024680-d0d8e180-15c0-11ea-9dd5-17e32c3ff84d.png">

**Comment by ruwiniwj** [comment]
> A similar issue is that only some widgets have this blue color background, where as some widgets doesn't have it.
> 
> _Without background:_
> <img alt="without background" width="1038" src="https://user-images.githubusercontent.com/20040505/70024679-d0d8e180-15c0-11ea-82f2-876065aa2eef.png">
> 
> _With background:_
> <img alt="with background" width="549" src="https://user-images.githubusercontent.com/20040505/70024680-d0d8e180-15c0-11ea-9dd5-17e32c3ff84d.png">

This is tracked with a separate issue https://github.com/wso2/analytics-apim/issues/866
