### ISSUE TITLE
APIM Analytics is not tested with DB2 and Informix DBs

### ISSUE THREAD

**Issue by RAVEENSR** [wso2/analytics-apim#846]
**Description:**
APIM Analytics is not tested with DB2 and Informix DBs.

**Suggested Labels:**
Improvement

**Suggested Assignees:**

**Affected Product Version:**
APIM Analytics 3.1.0-m2

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by TanyaM** [comment]
@RAVEENSR : Please test and update https://apim.docs.wso2.com/en/latest/Learn/Analytics/configuring-apim-analytics/#step-4-configure-databases

**Comment by RAVEENSR** [comment]
Updated the above mentioned doc in https://github.com/wso2/docs-apim/pull/606

**Comment by RAVEENSR** [comment]
APIM Analytics is now supporting DB2 databases. Relevant PRs are stated below which are used to add the DB2 support.

Carbon Coordination:
https://github.com/wso2/carbon-coordination/pull/62

Persistence:
https://github.com/wso2/carbon-analytics/pull/1773

Carbon Dashboards:
https://github.com/wso2/carbon-dashboards/pull/1202

Business rules:
https://github.com/wso2/carbon-analytics/pull/1772

Permission Provider:
https://github.com/wso2/carbon-analytics-common/pull/730

Carbon data provider:
https://github.com/wso2/carbon-analytics/pull/1771

Repo version upgrade:
https://github.com/wso2/analytics-apim/pull/904

**Comment by RAVEENSR** [comment]
Since API Manager 3.0.0 and 3.1.0 is not going to have the support for Informix for now closing the issue as DB2 support as given.
