### ISSUE TITLE
"ID token signature validation failed." error occurred in dashboard

### ISSUE THREAD

**Issue by RAVEENSR** [wso2/analytics-apim#851]
**Description:**
The following error occurred in the dashboard when trying to logout from the dashboard. This happens after a token is being refreshed.

<img width="1675" alt="IdTokenError" src="https://user-images.githubusercontent.com/19996612/70230482-6e2d4480-177e-11ea-9b0b-8e76c83e8f65.png">

**Suggested Labels:**
Bug

**Suggested Assignees:**
@RAVEENSR 

**Affected Product Version:**
APIM Analytics 3.1.0-m3 

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Wait for the token to be refreshed. Then try to logout from the dashboard. .

**Related Issues:**

**Comment by TanyaM** [comment]
Closing since https://github.com/wso2/carbon-analytics/pull/1767 is merged.

**Comment by RAVEENSR** [comment]
This PR fixes this issue in business rules web component -> https://github.com/wso2/carbon-analytics/pull/1769
