### ISSUE TITLE
API usage by applications chart needs to be implemented

### ISSUE THREAD

**Issue by fazlan-nazeem** [wso2/analytics-apim#870]
APIM Analytics 2.6.0 WUM updated distribution has a chart that will list down usage of APIs by applications. This chart is not implemented in 3.0.0.

**Comment by ruwiniwj** [comment]
<img width="1380" alt="Screen Shot 2019-12-13 at 11 52 21 AM" src="https://user-images.githubusercontent.com/20040505/70774453-59fdce80-1da0-11ea-86bb-eb3e33e7b707.png">
