### ISSUE TITLE
Track changes from APIM analytics 3.0.0 to 3.1.0 

### ISSUE THREAD

**Issue by ruwiniwj** [wso2/analytics-apim#871]
**Description:**
Track changes from APIM analytics 3.0.0 to 3.1.0 
- DB migration (https://github.com/wso2/analytics-apim/issues/863)
- SSO for business rules
- Split the 'Overall API Stats' widget (https://apim.docs.wso2.com/en/latest/Learn/Analytics/AnalyzingAPIMStatisticsWithBatchAnalytics/viewing-api-statistics/#overal-api-stats) into 2 widgets as 'API Availability' and 'API Ratings'.
- Introduce lerna to manage widgets
- Introduce `common-lib` package to reuse common code across widgets

**Comment by ruwiniwj** [comment]
- Overall API Usage improvements to select APIs(https://github.com/wso2/analytics-apim/pull/879)
- Add version data to Overall API Usage(https://github.com/wso2/analytics-apim/pull/895)
- Add api version and creator to publisher faulty stats widgets(https://github.com/wso2/analytics-apim/pull/880)

**Comment by ruwiniwj** [comment]
- Graphql support(https://github.com/wso2/analytics-apim/pull/848)

**Comment by RAVEENSR** [comment]
- DB2 Support(https://github.com/wso2/analytics-apim/issues/846)
- Mircogateway gRPC service feature(#912 and #916)
- PDF Report generation feature(#909, #913, #914, #915)
- Remove AM_DB path from worker deployment.yaml file (#890 and #893)

**Comment by RAVEENSR** [comment]
Add API usage by applications chart(https://github.com/wso2/analytics-apim/issues/870)

**Comment by pahans** [comment]
Add widget generator tool

**Comment by ruks** [comment]
Closing since 3.1.0 release is done.
