### ISSUE TITLE
Update meterial UI 3.x to 4.x

### ISSUE THREAD

**Issue by pahans** [wso2/analytics-apim#888]
**Description:**
Need to migrate to v4 from v3 https://material-ui.com/guides/migration-v3/
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ruks** [comment]
Closing the issue since SP analytics is deprecated.
