### ISSUE TITLE
Improving analytics reporting

### ISSUE THREAD

**Issue by tmkasun** [wso2/analytics-apim#889]
**Description:**
Currently, when we generate a report in the analytics dashboard it takes a screenshot of the visible part of the page and downloads it as PDF.

IMHO , We need to improve this capability to provide cleaner printable reports. The screenshot of the page is not paper friendly and widgets go out of aligning when report is generated in low resolution.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by fazlan-nazeem** [comment]
fixed with https://github.com/wso2/analytics-apim/pull/909 
Please note that only a request summary report is available at the moment. We are planning to provide other reports in future releases.
