### ISSUE TITLE
Move CustomTable and CustomTableHead components to CommonLib

### ISSUE THREAD

**Issue by ruwiniwj** [wso2/analytics-apim#896]
**Description:**
The [`CustomTable`](https://github.com/wso2/analytics-apim/blob/master/components/org.wso2.analytics.apim.widgets/APIMApiBackendUsageSummary/src/CustomTableHead.jsx) and [`CustomTableHead`](https://github.com/wso2/analytics-apim/blob/master/components/org.wso2.analytics.apim.widgets/APIMApiBackendUsageSummary/src/CustomTableHead.jsx)  components used in many analytics widgets can be moved to the `CommonLib`.

**Comment by pahans** [comment]
Postponed all refactorings because of upcoming changes to UI.

**Comment by ruks** [comment]
@pahans @ruwiniwj Is this already done?

**Comment by ruwiniwj** [comment]
@ruks no this is not done. This needs considerable restructuring so won't be feasible for this release.

**Comment by ruks** [comment]
Closing the issue since SP analytics is deprecated.
