### ISSUE TITLE
wso2 3.0.0 analytics dashboard not loading 

### ISSUE THREAD

**Issue by kalevivek11** [wso2/analytics-apim#908]
I am following link
https://apim.docs.wso2.com/en/latest/Learn/Analytics/configuring-apim-analytics/#quick-setup

database: Mysql

steps to reproduce:

keep analytics and apim(ALL-IN-ONE) in same directory
change the database connections
start worker profile
start apim
start dashboard

Getting message 
rification.
[2020-01-15 10:50:29,388]  INFO {org.wso2.carbon.uiserver.internal.deployment.listener.AppTransportBinder} - Web app 'analytics-dashboard' is available at 'https://172.30.162.81:9643/analytics-dashboard'.

**BUT nothing is loading
![analyticsDashboard2](https://user-images.githubusercontent.com/10954248/72407719-7ff30600-3786-11ea-928b-2a94449294f7.JPG)
**

**Comment by fazlan-nazeem** [comment]
@kalevivek11 Can you check whether publisher, devportal UIs are loading fine in your browser. Also, can you make sure APIM was up and running when you tried to load the analytics-dashboard?

**Comment by RAVEENSR** [comment]
@kalevivek11 According to your screen shot you are using Microsoft Edge or Microsoft Internet Explorer. Can you check with the Google Chrome latest version? If the problem still exists, kindly share your worker deployment.yaml file, dashboard deployment.yaml file and API Manager deployment.yaml file for further investigation.

**Comment by fazlan-nazeem** [comment]
We assume this is a config issue. Hence closing.
