### ISSUE TITLE
Update React version from 16.4.0 to latest

### ISSUE THREAD

**Issue by pahans** [wso2/analytics-apim#933]
**Description:**
React 16.4 is around 2 years old. We need to update to latest React. This will be the basis for pending features theming, improving widget API.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ruks** [comment]
@pahans can you please update the issue with current status?

**Comment by pahans** [comment]
this is done.
