### ISSUE TITLE
Date time range widget goes to two lines in some resolutions

### ISSUE THREAD

**Issue by pahans** [wso2/analytics-apim#982]
**Description:**
<img width="805" alt="Screen Shot 2020-02-18 at 12 24 02 PM" src="https://user-images.githubusercontent.com/1552869/74715274-26cd3500-5252-11ea-98e4-2ea4e867b951.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by TanyaM** [comment]
Shall we change the layout of this page also allowing the date time picker to take the entire horizontal container?

**Comment by ruwiniwj** [comment]
As mentioned earlier, this can be resolved by increasing the widget width. Hence closing this issue.
