### ISSUE TITLE
Need a script to generate dummy data for manual testing

### ISSUE THREAD

**Issue by pahans** [wso2/analytics-apim#989]
**Description:**
Running APIM, configuring, invoking,  then wait for data is time-consuming for testing we need a script to generate dummy data.
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by TanyaM** [comment]
@fazlan-nazeem : Can't we use that traffic tool that you mentioned offline?

**Comment by fazlan-nazeem** [comment]
This tool can be used for this purpose.  https://github.com/ThaminduDilshan/product-apim-tooling/tree/master/apim-traffic-tool
