### ISSUE TITLE
Analytics for web socket apis not working properly

### ISSUE THREAD

**Issue by TanyaM** [wso2/analytics-apim#997]
**Description:**
Several widgets in the publisher dashboard show incorrect stats for web socket apis.

Created apis widget has 2 apis ( 2 web socket apis and 1 rest api ) and all three apis are invoked atleast once.

<img width="577" alt="created_apis" src="https://user-images.githubusercontent.com/3957104/75138414-2a5c3280-5710-11ea-9c9d-2ba962e84914.png">

But the usage summary widget doesn't show the stats for SecondWebsocket api. Instead the hit count of SecondWebsocket api is aggregated into the EchoWebsocket api

<img width="781" alt="overall_api_usage" src="https://user-images.githubusercontent.com/3957104/75138471-51b2ff80-5710-11ea-8f43-d879cc64e715.png">

There are similar issues in the other widgets in the same page for web socket apis.

The database also contains incorrect data. Hence most probably an issue in the data aggregation level. 

<img width="583" alt="websocket" src="https://user-images.githubusercontent.com/3957104/75138664-c0905880-5710-11ea-974c-b6a37b5970b7.png">

**Affected Product Version:**
3.1.0-beta

**Steps to reproduce:**
1. Create one web socket api and one rest api, invoke them and view the widgets in Usage Summary page of the publisher api.
2. Stats shown is correct.
3. Create another web socket api ( so 2 web socket apis and 1 rest api in total ) and invoke the second web socket api
4. Refer the widgets in the same page and stats for the first web socket api is not shown now. Instead, the aggregated hit count is shown under the second web socket api.

**Comment by fazlan-nazeem** [comment]
fixed with https://github.com/wso2/carbon-apimgt/pull/8263
